### ISSUE TITLE
Add Optional Memorial of Our Lady of Loreto

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#106]
[Pope Frances decreed, via the Congregation for Divine Worship and the Discipline](https://www.vaticannews.va/en/church/news/2019-10/feast-of-our-lady-of-loreto-added-to-general-calendar.html) that the optional memorial of Our Lady of Loreto should be added to the `general.js` on 10 December 2019.

**Comment by jarosz** [comment]
It's already merged. Closing.
