### ISSUE TITLE
Duplicate celebration key of St Nicholas, Bishop

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#107]
In `greece.js`, there we use the `saintNicholas` key, which should be replace by `saintNicholasBishop`. Then, the `saintNicholas` key should be removed from `en.js` (no other locale contains that key already).

**Comment by emagnier** [comment]
I'm changing the label to `localization`, to make the difference between romcal bugs and anything related to localization (duplicated keys, missing keys...) in the issue tracker.
FYI I also created a similar label for everything related to celebrations.
