### ISSUE TITLE
Convert Types Array to Dictionary in types.js

### ISSUE THREAD

**Issue by jarosz** [romcal/romcal#109]
Issue #38 was fixed, but if Types was a Dictionary it would improve code readability.

So Types[6] would change into Types.OPT_MEMORIAL.

**Comment by emagnier** [comment]
Yes this is something that bother me too :)
Changing it to a Map object might be a good solution to make it a dictionary.

**Comment by tukusejssirs** [comment]
@jarosz & @emagnier: You have my ‘approval’. :smiley:

**Comment by jarosz** [comment]
It was impossible to simply replace Array with Map, because lib/Calendar.js relies heavily on the order of celebration types.

I have replaced hardcoded entries, and I think more should be changed (like _.head( Types ) and _.last( Types ).

**Comment by tukusejssirs** [comment]
I would say that this issue should be (or, practically, already is) assigned to @emagnier, so I take the courage to assign it to him. :)

**Comment by emagnier** [comment]
Was fixed here #114. Closing.
