### ISSUE TITLE
feast name: The Exaltation of the Holy Cross or The Triumph of the Cross

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#11]
You used the latter in `locales/en.json`, while the [wikipedia](https://en.wikipedia.org/wiki/Feast_of_the_Cross) states that the former is the translation of the Roman Missal (does not states the edition—probably should be checked in _editio typica tertia_) and the latter is the translation from Roman Missal (1973). Consider the change to the Exaltation of the Holy Cross.

I think the English translation from Roman Missal editio typica tertia (2011) should be used for any and all of the feasts. On the other hand, we in Slovakia have editio typica altera only, therefore I’d correct my previous statement (sentence) to this: alway used the translation of feast names from the latest Roman Missal translation in a particular language.

**Comment by pejulian** [comment]
The fix is commited to `git` and will be released as part of `romcal v1.3.0`

**Comment by tukusejssirs** [comment]
Thanks. But I don’t think his should be included in the project `To do in Slovakian Liturgical Calendar`, as this is connected with English localisation.

**Comment by tukusejssirs** [comment]
This issue has not been fixed properly.

We need to do the following:
- remove `findingOfTheHolyCross` (from `en.js` and `peru.js`), as it is duplicate of `theExaltationOfTheHolyCross`;
- add `theExaltationOfTheHolyCross` to `general.js` ([src](https://en.wikipedia.org/wiki/General_Roman_Calendar#September)).

**Comment by jarosz** [comment]
> * add `theExaltationOfTheHolyCross` to `general.js` ([src](https://en.wikipedia.org/wiki/General_Roman_Calendar#September)).

I agree.

> * remove `findingOfTheHolyCross` (from `en.js` and `peru.js`), as it is duplicate of `theExaltationOfTheHolyCross`;

I don't agree. According to the quoted article, it is not a duplicate, but a separate feast in Peru, so it should be removed only from en.js.

**Comment by tukusejssirs** [comment]
@jarosz, you’re right. I somehow misread the whole thing (might have been too tired). :smiley:

**Comment by tukusejssirs** [comment]
@emagnier, I’ve just found out that this key is not translated in `fr.js` only (from `en.js`, `fr.js`, `it.js`, `pl.js` and `sk.js`, i.e. the currently supported languages).

I need you to supply me the translation of this feast. From [here](https://fr.wikipedia.org/wiki/F%C3%AAtes_de_la_Croix#Exaltation_de_la_Sainte-Croix,_14_septembre) I’ve got this: _Exaltation de la Sainte-Croix_. Is this correct? Can I use this?

**Comment by emagnier** [comment]
Yes it's the right translation.
