### ISSUE TITLE
`chile.js`: Fix the celebration on 14 July

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#115]
Tasks:
1. Remote that comment block.
2. Create a new key (localise it in `en.js`): `"saintCamillusDeLellisPriestOrSaintHenryBishopAndMartyr": "Saint Camillus de Lellis, priest, or Saint Henry, Bishop and Martyr"` (`sk.js`: `Svätého Kamila de Lellis, kňaza, alebo svätého Henricha`).
3. Define `saintCamillusDeLellisPriestOrSaintHenryBishopAndMartyr` celebration in `chile.js`.

**Comment by emagnier** [comment]
In french: `Saint Camille de Lellis, Prêtre, ou Saint Henri, Évêque et Martyr`
