### ISSUE TITLE
`ukraine.js`: Is `maryMotherOfTheChurch` a feast in Ukraine?

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#116]
@pejulian added this comment in the [`poland.js`](https://github.com/romcal/romcal/blob/romcal-es6/src/calendars/poland.js#L685), so I believe @jarosz should confirm this possible issue. Below is the relevant code.

```bash
// [pejulian] Needs confirmation: In Poland this day is a feast
    {
      "key": "maryMotherOfTheChurch",
      "type": Types[4],
      "moment": ( y => Dates.pentecostSunday( y ).add( 1, 'days'))( year ),
      "data": {
        "prioritized": true,
        "meta": {
          "liturgicalColor": LiturgicalColors.WHITE
        }
      }
    },
```

**Comment by jarosz** [comment]
It's a memorial in general calendar since 2018. Some countries, dioceses and religious families who petitioned the Holy See were allowed to add this celebration to their particular calendars. It's been a feast in Poland since 1971 and it continues to be like that.

Sources mention, that it was celebrated like that in Argentina as well (e.g. https://www.ncronline.org/news/vatican/pope-adds-feast-mary-mother-church-universal-calendar), but I can't verify. It's not in romcal.

**Comment by tukusejssirs** [comment]
@jarosz, good to know that this is not an issue in `pl.js`. I just wanted you to confirm this. We should create a PR to remove comment.

As for the `argentina.js`, as this celebration is not listed in that calendar, I would keep it that way (the optional memorial from GRC is still loaded) … until someone with enough knowledge would improve this calendar.

**Comment by jarosz** [comment]
And what to do with ukraine.js? Is it confimed to be a feast?

**Comment by jarosz** [comment]
Managed to confirm, try if you can read it :)

![2019-12-15 23_00_01-Katnapt2019UA jpg (1920×1358)](https://user-images.githubusercontent.com/151552/70869997-b45c8200-1f8e-11ea-953c-632690e79aac.png)

**Comment by tukusejssirs** [comment]
Although, I can read it, how  do you know what celebration rank (type) it is? But in this I would partially rely on the [Wiki](https://en.wikipedia.org/wiki/General_Roman_Calendar#Ukraine), which clearly states it is a feast, therefore that comment should be removed too.

By the way: good catch! :smiley:

**Comment by jarosz** [comment]
I've found it also on other website: Пресвятої Діви Марії, Матері Церкви, свято
https://risu.org.ua/ua/index/resourses/calendar/calendar_archive/74133/
