### ISSUE TITLE
Add (group) calendar for China, Hong Kong and Taiwan

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#118]
We could add this calendar based on [Wiki](https://en.wikipedia.org/wiki/General_Roman_Calendar#China,_Hong_Kong_and_Taiwan).

**Comment by tukusejssirs** [comment]
@emagnier: I have labelled this as `celebration`, but I am not sure if it it the right place. Should we create a new label named `calendars`?

**Comment by emagnier** [comment]
We can keep the `celebration` label for the moment.

**Comment by tukusejssirs** [comment]
Just a side-note: when we want to fix an issue that is in the `backlog`, first we should move it to next version milestone (currently: `v1.3.0`) and then work on it. :smiley:

Anyway, I’ll create a doc for this in the Wiki (if you think that we should add this and all other docs to the repo files exclusively, comment on this matter in #57).
