### ISSUE TITLE
Add calendars for dioceses (and towns/cities)

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#13]
| Date | Diocese/Ordinariate | Saint | Feast Type |
|--------|--------------------------|--------|----------------|
| 20th Jan | Ordinariate of Military Forces and Armed Corps | Saint Sebastian, Martyr—main patron of the Ordinariate and of the Cathedral | Feast in Ordinariate, Solemnity in Cathedral |
| 23rd Jan | Bratislava | Saint John the Merciful, bishop | Memorial (only in Cathedral) |
| 14th Feb | Žilina | Saint Cyril, monk, and Methodius, bishop – main patrons of diocese | Feast |
|10th Mar | Bratislava | Anniversary of Consecration of St Martin of Tours Cathedral | Feast in Diocese, Solemnity in Cathedral |

If consecration anniversary falls on Sunday, it’s moved to Monday.

I have not finished the list for I create the list manually. As soon as I find new one (and also have some time), I add it to this list in this comment.

**Comment by tukusejssirs** [comment]
As this issue is not only Slovak celebrations, but any celebration specific to a particular dioces/city/town, i’ve renamed the issue. It is related to #48.

**Comment by emagnier** [comment]
Romcal `v3` now allows diocesan calendars.
