### ISSUE TITLE
Add an option to query specific `season` or `key`

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#161]
Currently, we can query the dates only by `month` and/or `day`, and they can be sorted by specific groups.

While I was creating [the script to get the date of the First Sunday of Advent](https://github.com/romcal/romcal/issues/75#issuecomment-579892852), I wanted to get only the date of a specific celebration, but `key: "1SundayOfAdvent"` nor `season: "advent"` did not work.

**Comment by emagnier** [comment]
Theses methods will get what you want:
- `Romcal.Dates.firstSundayOfAdvent(year)`
- `Romcal.Calendar.calendarFor({ query: { group: 'liturgicalSeasons' } }).Advent`

**Comment by tukusejssirs** [comment]
I see I am not good at JS. Thanks. :smiley:
