### ISSUE TITLE
Unify the config variables / option names

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#163]
I think we might want to unify the following two config variables / option names:
- `ascensionOnSunday`;
- `corpusChristiOnThursday`;
- `epiphanyOnJan6`.

I think that both should be in form `*OnSunday` to override the default config of `general` calendar.

This might be, however, considered as an API-braking change, therefore I have put it into the `v2.0.0` milestone.

**Comment by pejulian** [comment]
*corpusChristiOnSunday*
#203e284f80d1b2e138a5b4ecd1a3252e5731b49f

**Comment by tukusejssirs** [comment]
LGTM.

Anyway, even the canary builds should be `v2.0.0`.

**Comment by emagnier** [comment]
Addressed on https://github.com/romcal/romcal/pull/250.
