### ISSUE TITLE
skSK: Our Lady of Sorrows is a Solemnity in Slovakia

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#17]
It is for Our Lady of Sorrows (literally from sk: Virgin Mary of Seven Sorrows or Seven-Sorrowful Virgin Mary) is the patron of Slovakia.

**Comment by tukusejssirs** [comment]
And I found that you created `ourLadyOfSorrowsPatronessOfSlovakia` key, too, which is a duplicate of `OurLadyOfSorrows` (the latter should be used instead of the former as they represent the same feast).

**Comment by pejulian** [comment]
Hi @tukusejssirs,

Thanks for spotting the duplicate.
I've made the fix accordingly with some test cases.

**Comment by tukusejssirs** [comment]
> [@tukusejssirs]
> And I found that you created `ourLadyOfSorrowsPatronessOfSlovakia` key, too, which is a duplicate of `OurLadyOfSorrows` (the latter should be used instead of the former as they represent the same feast).

According to the current romcal rules (however, it was back then too), these two keys are not duplicates _per se_. I’ll re-introduce `our_lady_of_sorrows_patroness_of_slovakia` in #213 until we fix #201.

@emagnier, should keep the [test of this key](https://github.com/romcal/romcal/blob/7e33ab07485477e008c52cdd19f5f7bb7f3d5469/__tests__/calendar_date_overrides.test.ts#L492) where it is or should I move it (and thus separate it from the `our_lady_of_sorrows` key tests)?

**Comment by emagnier** [comment]
Lets' keep it with the others.
