### ISSUE TITLE
Early/Later Ordinary Time

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#170]
Though I understand the reason behind the division, but there is Ordinary Time only, no early/later Ordinary Time.

Should we not remove these and keep only Ordinary Time?

**Comment by emagnier** [comment]
We need to keep them for some internal reasons. But instead I suggest that we could ouput multiple season.

Like:
- ordinary time, early ordinary time
- ordinary time, later ordinary time
- lent, holly week

The most general first, the most specific then.

**Comment by tukusejssirs** [comment]
Yes, I what you mean and I agree. But what would be output if you want `ordinary time` and `early ordinary time`? The output would be the same as `ordinary time`, would it be not?

**Comment by emagnier** [comment]
Please have a look to the new Object / JSON outputed by romcal: https://github.com/romcal/romcal/blob/_F-TypeScript/docs/data-output.md#json-structure

[Seasons](https://github.com/romcal/romcal/blob/_F-TypeScript/docs/data-output.md#liturgical-seasons) and Liturgical [periods](https://github.com/romcal/romcal/blob/_F-TypeScript/docs/data-output.md#liturgical-periods) are now 2 separated properties. And `seasons` strictly follow the official liturgical seasons, while `periods` give official and non-official data.

**Comment by emagnier** [comment]
Addressed on https://github.com/romcal/romcal/pull/250.
