### ISSUE TITLE
Immaculate heart of Mary is Memorial ?

### ISSUE THREAD

**Issue by emagnier** [romcal/romcal#172]
`immaculateHeartOfMary` have type rank set to `FEAST`. But I think it should be `MEMORIAL` (at least it is in France and United-States). But I guess it's an error and it should be a `MEMORIAL` in the `general.js` calendar as well.

Futhermore there is a comment just above mentioning `// Memorials`.

**Comment by tukusejssirs** [comment]
Indeed you are right. I have checked it at [Universalis](https://www.universalis.com/calendar.htm), [Wiki](https://en.wikipedia.org/wiki/General_Roman_Calendar#June) and [lc.kbs.sk](https://lc.kbs.sk/?den=20200620).

**Comment by tukusejssirs** [comment]
The fix of this is quite simple, but we still have a minor issue of the date calculation. The [Wiki]() says:

> Saturday following the second Sunday after Pentecost: Immaculate Heart of Mary – Memorial _(in years when this memorial coincides with another obligatory memorial, as happened in 2014 [28 June, Saint Irenaeus] and 2015 [13 June, Saint Anthony of Padua], both must be considered optional for that year)_

And it sources [this notification](https://www.vatican.va/roman_curia/congregations/ccdds/documents/rc_con_ccdds_doc_20000630_memoria-immaculati-cordis-mariae-virginis_lt.html).
