### ISSUE TITLE
`Saint` vs `Saints` in celebration names that include `companions`. Simplifying the l10n key nanes

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#174]
The inconsistency lays in the word `saint(s)` or `blessed(s)` (the _canonisation level_).

For `blessed(s)`, we use it consistently: in singular. For `saint(s)`, we use `saint` 18 times and `saints` 11 times.

Now, we need to decide how will we name the celebrations that include `companions`. Which option is (grammatically) correct?

Take for example these two options (currectly, these are duplicates we need to fix; these keys made me notice this issue):
1. singluar: _Saint Augustine Zhao Rong, Priest and Companions, Martyrs_;
2. plural: _Saints Augustine Zhao Rong, Priest, and Companions, Martyrs_.

In the official Sloval liturgical calendar (_Direktorium_), we use the plural version, which might be _grammatically_ more correct, as we (may) want to say that not only _Augustine Zhao Rong_ is saint, but also _his companions_. But this might not be actually _true_, because not all the companions _must_ be saints (some of them might be blesseds).

As part of the _saints metadata separation process_ (#154), I want to list all the companions (and other _collective names of the celebrated persons_, like the _Vietnamese martyrs_) and this _trueness dilemma_ might be solved by checking if all the _non-named persons_ are of the same canonisation level as the _named ones_: if true, use plural option; if false, use singular option unless we name two or more persons who have the same canonisation level.

Any ideas, @pejulian, @emagnier?

**Comment by emagnier** [comment]
FYI In the official francophone proper calendars, they use the singular version.
And I think it's better because we separate better each entities/parts:
1. Saint Augustine Zhao Rong, Priest
2. Companions
3. Martyrs (<= the common titles for entities 1 and 2)

Programatically it will be also easier to combine them that way.

**Comment by tukusejssirs** [comment]
Okay, I have asked a friend of mine (a Slovak teacher) what is the grammatically correct option in Slovak language. As for me, _formally_ I think that the _singular option_ is better because we should not take the _companions_ into account (unlike _named_ multiple sainf of the same canonisation level, like _Saints Peter and Paul, apostles_). Then I’ll come back and provide the correct Slovak version.

As for the separation, I agree. I have already suggested this from the l10n point of view in #154.

**Comment by tukusejssirs** [comment]
After consulting with two Slovak language teachers (one of them proofreads books and other kind of written articles), and I have found two things (from grammatical point of view):
1. In Slovak, it does not matter if _saint/blessed_ word is in singular or plural in case of one named person plus _companions. Both are grammatically correct.
2. I was proven wrong that the comma before _a_ (Slovak conjuction, equivalent of the English _and_) is incorrect even when the titles between first person and the second (and other) person(s) (or _companions) don’t match [like it is in case of St Augustine Zhao Rong, Priest, (← this comma) and companions]. On the other hand, it is written incorrectly in the official liturgical books too.

Now, I suggest that:
- when there is **only one named person** with or without the collective _companions_ (like the above-mentioned celebration), we should use the canonisation level in **singular**;
- when there are **more than one named persons** with or without the collective _companions_ (like _Saints Cornelius, Pope, and Cyprian, Bishop, Martyrs_), we should use the canonisation level in **plural**.

[`sk.js`] Furthermore, I’ll will correct the above-mentioned comma issue even though it is in contrary with the current official books. I’ll try to get in touch with the Slovak Liturgical Commission and suggest the correction, but I have heard that the Slovak liturgists does not pay heed to the grammer.

---

@emagnier, @pejulian, I’d like to hear your thoughts if you agree with my proposals. I am in the middle of duplicates removal (and other issues mentioned in [this comment](https://github.com/romcal/romcal/issues/154#issuecomment-585094970) by me), so I could deal with this issue too, unless you think that this issue should be dealt with in a separate PR.

**Comment by tukusejssirs** [comment]
> [@tukusejssirs]
> Now, I suggest that:
> - when there is **only one named person** with or without the collective _companions_ (like the above-mentioned celebration), we should use the canonisation level in **singular**;
> - when there are **more than one named persons** with or without the collective _companions_ (like _Saints Cornelius, Pope, and Cyprian, Bishop, Martyrs_), we should use the canonisation level in **plural**.

@pejulian, @emagnier, what do you think about this? I’d like to solve this issue and add this rule into the [Localisation rules](https://github.com/romcal/romcal/wiki/Localization-rules) (of course, when we use a DB and separate the personal celebrations by metadata and join them in the celebration definitions, this rule should be moved into the romcal logic).

**Comment by emagnier** [comment]
Good point 👍. But instead I would recommend removing the canonisation level (saint & blessed), especially for people with a blessed level that are becoming a saint.

More generally, I would recommend removing everything in keys that can potentially change (like Doctors). And only keep information that will never change, like Apostle, Priest... (information that is still useful to identify the person).

Because we should avoid as much as possible to modify keys, since third apps based on Romcal could lean on theses keys.

**Comment by tukusejssirs** [comment]
@emagnier, I agree with you that the _key_ should contain only such information (words) that are sufficient to indentify the celebration/person and thus make that key unique. From my point of view, however, even titles like `priest` or `pope` (which won’t change) are not necessary at times when the person name itself is unique (e.g. the person has surname-like name like St Ignatius of Loyola).

From my point of view the proper fix for all these l10n issues we have (and all the current fixes are quite laborious) would be fixed with proper l10n tool, using a DB (like we have already discussed in #154), separation of the celebration/person metadata into (let’s say) DB columns, and localising the _metadata_ only (personal names would be also considers as metadata). I know we currently don’t work on this, but I wish we would start working on this as the bugs always come when I start working on _anything_ related to l10n.

Anyway, the keys should be automatically generated and IMHO they could be even integer numbers (like in SQL the sequences). And I think that the third-party apps should not rely on our _internal_ keys in the future; they should use some human readable identifiers (just like our current keys) that would _search_ for the right celebration (they could/should be smart enough and use fuzzy search that even if the user makes a type in the celebration name, romcal would output the closest match).

---

Now back to the current issue; even when we remove the canonisation level from the keys, this issue still would be valid, because it is not only related to the keys, but also to the values.

**Comment by emagnier** [comment]
About keys, no need to do something too complicated. We define keys and we keep them, that's it.
And rules are easy to define: we remove saint/blessed/doctors... (anything that can change), and we simply keep everything else that give good information about the person (priest, pope, apostle, and any other qualifications or name), so we are sure who is the person behind a key, without much risk to get it wrong. This isn't very important if keys don't have all exactly the same structure (it's only a codename, useful for third-party apps), as long as they are unique, and understandable & human readable for developers (so no integer numbers please). And it we realize in the future we forgot a special title or name for someone, too bad, we keep his existing key.

As a developper using romcal for different projects, this is the only thing I would like, and being sure keys will not be updated too often from Romcal. So I don't have to update my database or codebase too often each time I want to update romcal in my project (and being worried about that).

And as a romcal contributor, I think it's a bad idea to try to generate them from any tooling (it's a gate for potential bugs or issues): it will complexity things and I believe it's not worth it here.

---

> Now back to the current issue; even when we remove the canonisation level from the keys, this issue still would be valid, because it is not only related to the keys, but also to the values.

You are right, needs are differents for values of keys.

**Comment by tukusejssirs** [comment]
Okay, I get it: KISS. :smiley:

Still I with to have a separate DB (or whatever, even files like we already have) where there we would have separate celebration/person metadata (name, surname, titles usually used [i.e. no patrons of any part of the world], canonisation level, etc) which would be easier to localise and maintain from l10n point of view. Of course, we would need to define the format for each and every locale, but I don’t is as a problem (we can use some kind of variables/placeholders like `{{name}}` and we could even let the users define their own format).

---

Anyway, in Latin they use always plural `Ss.` (saints), even when there is only one explicitly stated person name followed by `sociorum` (companions).

**Comment by emagnier** [comment]
Sure, this is all the things we will have to consider to improve all the localization, taking into account all languages specifics and possible customisations.

And on a side note, I'm happy to see the Latin translation maybe coming soon into romcal!

**Comment by tukusejssirs** [comment]
I am still working on `la.ts`. I try to localise all the keys from `en.ts` into `la.ts`; I hope I finish it before you’ll find the time to realease a new version in August. Anyway, the keys from `general.ts` are already localised, but I have not yet pushed the code.
