### ISSUE TITLE
Institution of the Sunday of the Word of God

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#176]
On 30 September 2019, Pope Francis [instituted](http://www.vatican.va/content/francesco/en/motu_proprio/documents/papa-francesco-motu-proprio-20190930_aperuit-illis.html) the Third Sunday in Ordinary Time as _Sunday of the Word of God_.

I think romcal should be updated according to this.

**Comment by pejulian** [comment]
I've added the fix for this to the typescript branch.

**Comment by tukusejssirs** [comment]
@emagnier, just a reminder: this issue should be closed when the TS branch will be merged into `master`.

**Comment by emagnier** [comment]
Addressed on https://github.com/romcal/romcal/pull/250.
