### ISSUE TITLE
`liturgicalColor`: return localised name instead of hexadecimal value

### ISSUE THREAD

**Issue by emagnier** [romcal/romcal#177]
Actually, romcal return a color key and an hexadecimal value.

```javascript
{
  data: {
    meta: {
      liturgicalColor:
        {
          key: '', // 'RED' | 'ROSE' | 'PURPLE' | 'GREEN' | 'WHITE' | 'GOLD'
          value: '' // hexadecimal value
        }
      }
    }
  }
}
```

Keys and hexadecimal values are already doublons, since colour key names can also be used in different coding languages, including HTML.

Instead of returning an hexadecimal value, it would be more useful to return a localised name. Furthermore, we might use different colour palette (in other words, different colour code), so hexadecimal value will be again useless and could lead to confusion.

For exemple, romal should return instead:
```js
// In English:

liturgicalColor:
{
  key: 'RED',
  value: 'red'
}
```
```js
// In French:

liturgicalColor:
{
  key: 'RED',
  value: 'rouge'
}
```

**Comment by tukusejssirs** [comment]
1. On the localisation: I have already suggested that, see [the sheet](https://docs.google.com/spreadsheets/d/1c9YWtfntpxy0r0rg0mfowJ2v-yKW6wSMmNzyY3umBU4/edit#gid=2129240542).

2. Although I agree that we should return only only value for the colour, I think it might be a better idea to provide a general romcal option to let the user configure how it should be returned; see _litColor_ in #156.

3. On custom hex colours, see _litColorCustomHex_ in #156.

**Comment by emagnier** [comment]
In my point of view, romcal should stay agnostic of all color shade or themes variations. It's not romcal's jobs to return an hexadecimal value. The color key name is enough to specify the general color of a celebration, and it gives all the necessary data to do what we want then, outside of romcal.

**Comment by tukusejssirs** [comment]
Okay, then I think that the `litColor` and `litColorCustomHex` could be implemented in the `romcal-api`. What do you think?

**Comment by emagnier** [comment]
Nope ;) the goal of romcal-api is just to package and expose the romcal features in a different manner for specific needs, not to add new features on top of romcal.

If you need hexadecimal values, you should manage these customisation on you own app/website.

**Comment by tukusejssirs** [comment]
Okay, then.

Could you comment on #156 to in order to decide which parts of that issue might be implemented and which won’t be implemented? We might want to moved out the parts which might be implemented into separate issues.

**Comment by pejulian** [comment]
I definitely agree that `romcal`'s output should strive to be as agnostic as possible.

To this end, I've done some changes where:

1. I removed the hex color code from `LiturgicalColors`
2. Added a new `localizeLiturgicalColor` function that will use the key of a `TLiturgicalColor` to find a localizable value for the given color key.
3. Added the English color names to `en.ts`
4. Added logic that attempts to localize all calendar source items that have a `liturgicalColor` meta property.

The outcome of these changes look like this:

```json
{
  "key": "saintSylvesterIPope",
  "name": "Saint Sylvester I, Pope",
  "date": "2020-12-31T00:00:00.000Z",
  "type": 6,
  "data": {
    "meta": {
      "psalterWeek": {
        "key": 3,
        "value": "Week IV"
      },
      "cycle": {
        "key": 1,
        "value": "Year B"
      }
    },
    "season": {
      "key": "CHRISTMASTIDE",
      "value": "Christmas"
    },
    "calendar": {
      "weeks": 53,
      "week": 1,
      "day": 366
    }
  },
  "_id": 580,
  "_stack": 2,
  "base": {
    "key": "seventhDayInTheOctaveOfChristmas",
    "name": "7th day in the Octave of Christmas",
    "date": "2020-12-31T00:00:00.000Z",
    "type": 8,
    "data": {
      "season": {
        "key": "CHRISTMASTIDE",
        "value": "Christmas"
      },
      "meta": {
        "titles": [],
        "psalterWeek": {
          "key": 3,
          "value": "Week IV"
        },
        "liturgicalColor": {
          "key": "WHITE",
          "value": "White"
        },
        "cycle": {
          "key": 1,
          "value": "Year B"
        }
      },
      "calendar": {
        "weeks": 53,
        "week": 1,
        "day": 366
      }
    },
    "_id": 364,
    "_stack": 0
  }
}
```

Important points in this implementation:

1. It is entirely possible (and valid) if a celebration does not have any `liturgicalColor` assigned to it simply because it was defined without one. The end user will have to look into the `baseItem` to find the `liturgicalColor` to be used.
2. The base item (or overridden) celebration associated to the date item should almost always contain a `liturgicalColor` as its calendar source is most likely from `Seasons.ts` or `Celebrations.ts`.
3. On the occasion where both the base item and main celebration has no `liturgicalColor` assigned to it (if any), we might consider this a data quality issue where a color needs to be assigned to either date/celebration

**Comment by emagnier** [comment]
Yes, the base item (which is basically a `feria` or a `sunday`) must always have a `liturgicalColor`. If it doesn't have one, we can effectively consider that a critical bug. More exactly I think romcal should always provide `liturgicalColor` for any celebrations coming from the temporal calendar (computed from `Seasons.ts`), and I think this is already the case.

Then, base item exists to retrieve any default and contextual data (including `liturgicalColor`) which could be missing or needed in a current celebration.

But, related to the `liturgicalColor` coming from a sanctoral calendar (from `Dates.ts`, `calendar/**.ts`), I think we could also be able to compute them automatically. We might have exceptions (like `allSouls`), but generally all celebrations are `white`, except `martyrs` and `apostles` which are `red`, and `commemorations` (`opt_memories` during Lent and on December 17-24 in Advent) which inherit the color of the current feria/sunday (so generally `purple`).

FYI we already had a discussion about color computing here (for all celebration comming from a sanctoral calendar): #121

**Comment by tukusejssirs** [comment]
> 3. Added the English color names to `en.ts`

In my opinion, we should separate the l10n string into separate files based on the content. When we implement other stuff, a single file will become huge.

I suggest to create a folder per language (e.g. `src/locales/en/`) and in each language folder we would have the following files (for the regional languages like `enGB`, files that have no difference from the main lang like `en`, would not be created). Note that most of these won’t be created now, but later in the future when they would be used by the to-be-implemented features. Feel free to rename these files if you find better names for them.
- `celebrationKeys.ts` (same content as v1.3.x);
- `titles.ts` (titles of saints/blesseds);
- `canonization.ts` (`saint` and `blessed`);
- `seasons.ts` (liturgical seasons);
- `months.ts` (calendar months);
- `week_days.ts` (week days);
- `languages.ts` (names of languages);
- `bible_books.ts` (Bible book names);
- `numbers.ts` (number names);
- `colors.ts` (colour names);
- `calendars.ts` (calendar names);
- `subcalendar.ts` (subcalendar names; might be merged with `calendars.ts`);
- `continents.ts` (continent names);
- `countries.ts` (country names);
- `regions.ts` (region names; like `England`);
- `dioceses.ts` (diocese names; might be in a separate repo);
- `parishes.ts` (parish names; might be in a separate repo);
- `misc.ts` (other strings).

For more information on my suggestion (esp to see what exactly I suggest to include in those files), see [this spreadsheet](https://docs.google.com/spreadsheets/d/1c9YWtfntpxy0r0rg0mfowJ2v-yKW6wSMmNzyY3umBU4/edit#gid=2129240542) (look for similarly names sheet).

> ```json
>       "key": "CHRISTMASTIDE",
> ```

May I know why the season key is in all caps?

> ```json
> meta { ... }
> ```

Is it a one key? It contains the `meta` twice. Is it necessary?

> 1. It is entirely possible (and valid) if a celebration does not have any `liturgicalColor` assigned to it simply because it was defined without one. The end user will have to look into the `baseItem` to find the `liturgicalColor` to be used.

Why would the user need to check the `liturgicalColor` in two different places? Should it not be the romcal’s job to check if it defined in the celebration definition and if not, it should be automatically assigned (according to the rules; see #121)? (@emagnier provided [better explanation](https://github.com/romcal/romcal/issues/177#issuecomment-595714777).)

**Comment by emagnier** [comment]
Ok, but all the localisation issue is a bit out of scope from this topic.

> May I know why the season key is in all caps?

It's a naming convention for constants. Furthermore, having them uppercase will help to don't mix key and value (especially in English).

> Is it a one key? It contains the meta twice. Is it necessary?

It's not the same object. Current celebration and base celebration.

**Comment by emagnier** [comment]
Addressed on https://github.com/romcal/romcal/pull/250.
