### ISSUE TITLE
sort keys in locales `*mjs` files

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#18]
I partially suggested this in a [comment](https://github.com/pejulian/romcal/issues/10#issuecomment-370391673) of issue #10. But after some time of thinking, I think that they (general and national feasts/memorials) should be divided into months to be more transparent and that there won’t be any duplicates in the future.

Still, there should be some rules to abide or naming convension of the keys. Here are my suggestions/proposals:

(1) Drop Saint/Saints/Blessed except for Blessed Virgin Mary. Do not drop Holy (like in Holy Cross
(2) Probably, it would be nice to implement comments in `*.mjs` file (e.g. month names), but as far as I know `.json` (and probably `.mjs` too) does not support comments, therefore there’s a need of a parser/comments-remover (simplest way: using `sed` or `grep` before using the files). These comments would be only for separating the keys into groups which can be easily managed.

(3) I think that separating optional memorials from a single key into multiple ones would be better.

(4) **UPDATE:** Divide `national` group of keys into subgroups of calendar names (for which we use country names in `src/calendars`.

We/you need to decide what to do with priest/deacon/etc—we can't drop them altogether for sometimes they are the only way of distinction, therefore keeping them is necessary in my opinion.

**Comment by tukusejssirs** [comment]
I've never come in `*.mjs` – are the comments like in regular JavaScript?

**Comment by tukusejssirs** [comment]
Add 4th suggestion into the [first comment](https://github.com/pejulian/romcal/issues/18#issue-302355866) of this issue.

But still, I’d like to know if I can insert comments into `*.mjs` files. If not, I’d suggest to decide the comments format and them use a parser before using them in the program.

**Comment by tukusejssirs** [comment]
I’ve found that comments where already used in `src/calendars/poland.mjs`:

```bash
../calendars/poland.mjs:363:    // jarosz: Changed ourLadyOfMountCarmel to MEMORIAL
../calendars/poland.mjs-364-    {
../calendars/poland.mjs:365:      "key": "ourLadyOfMountCarmel",
../calendars/poland.mjs-366-      "type": Types[5],
../calendars/poland.mjs-367-      "moment": moment.utc({ year: year, month: 6, day: 16 }),
```

therefore I presume that commenting using two slashes (`//`) is already working.

**Comment by tukusejssirs** [comment]
Now, I think that subgroups can’t have names of countries, because some feasts are in multiple calendars, e.g. `saintFrancisSolanusPriest`:

```bash
$ grep -in -A2 saintFrancisSolanusPriest ../calendars/*
../calendars/argentina.mjs:93:      "key": "saintFrancisSolanusPriest",
../calendars/argentina.mjs-94-      "type": Types[5],
../calendars/argentina.mjs-95-      "moment": moment.utc({ year: year, month: 6, day: 24 }),
--
../calendars/bolivia.mjs:56:      "key": "saintFrancisSolanusPriest",
../calendars/bolivia.mjs-57-      "type": Types[4],
../calendars/bolivia.mjs-58-      "moment": moment.utc({ year: year, month: 6, day: 14 }),
--
../calendars/peru.mjs:29:      "key": "saintFrancisSolanusPriest",
../calendars/peru.mjs-30-      "type": Types[4],
../calendars/peru.mjs-31-      "moment": moment.utc({ year: year, month: 6, day: 14 }),
```

We/I must think of better naming, but the subgroups would be great in my opinion.

**Comment by tukusejssirs** [comment]
@pejulian, I’d like to know, what do you think of the following proposal of mine about sorting the keys in locales.

(a) general calendar keys would be sorted according to civil (Gregorian) calendar, i.e. the keys would be grouped by months (which would be indicated by comments).

(b) national calendar keys would be sorted first according to countries (calendars) the celebrations are celebrated in, an then according to civil (Gregorian) calendar. If a celebration is celebrated in multiple countries (calendars), the key would be listed only in the alphabetically first country (key group); in other countries (key groups), there would be only a comment, that the particular keys in that and that country (key group).

Then, another thing to deal with will be, when we (in the future) add a new key to `enUS.mjs`, how we‘ll make sure that they won't be missing from other locales and that they won’t be outdated.

**Comment by tukusejssirs** [comment]
I think we could close this issue, as the keys in the locales are already sorted. What do you think, @emagnier?

**Comment by emagnier** [comment]
Ok.
