### ISSUE TITLE
`_F-TypeScript`: Build and test

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#184]
I’ve just tried to build and test the `_F-TypeScript` branch.

I have installed it using `npm install` in the repo root. Then I opened `src/index.html` in Firefox. The following error occured:

```bash
TypeError: can't access property "calendarFor", window.romcal is undefined
```

![Screenshot from 2020-03-08 16-52-54](https://user-images.githubusercontent.com/5111894/76166222-e6781d00-6154-11ea-9e17-9de10e76141c.png)

The screenshot above was taken after I have fixed the missing language (`<html lang="en">`) and charset (`<meta charset="utf-8">`) specification.

Is there anything else needed to make it work?

**Comment by pejulian** [comment]
Hello @tukusejssirs ,

I could not reproduce the issue you faced.

I created a new folder on my desktop, copied the latest canary `romcal` folder that I `npm install`ed in another project and then created a simple `index.html` file to load the `/es5` script.

I then tried to:

1. Load the `index.html` file directly by dragging it into a new tab in my browser
2. Serve the `romcal-test` directory using a [simple HTTP server](https://www.npmjs.com/package/serve)

The output was as expected on both the tests above.

![image](https://user-images.githubusercontent.com/4044311/76175640-803cda00-61e8-11ea-97b0-3e284f6d6d95.png)

Attached here is the test folder I used for the above:
[romcal-test.zip](https://github.com/romcal/romcal/files/4304242/romcal-test.zip)

Could you post more details on the issue you're facing?

PS:- I made all these experiments using Chrome and IE11.

**Comment by tukusejssirs** [comment]
I think I’ve found my issue: Although I have run `npm install` in the cloned romcal repo root folder, but it did not create `dist/` folder and the files in it.

The other part of the problem lays in the `src/index.html` file itself: the one in the romcal repo (`_F-TypeScript` branch), misses the following part I’ve got from the one you gave me in the archive:

```html
    <script
      type="text/javascript"
      src="./romcal/dist/es5/vendor~romcal.bundle.es5.js"
    ></script>
    <script
      type="text/javascript"
      src="./romcal/dist/es5/romcal.bundle.es5.js"
    ></script>
```

Without this file the `src/index.html` won’t work.

---

Therefore, I have a question: how to build romcal (create `dist/` folder and the files in it) from cloned romcal repo? I understand, that the `npm install romcal@canary` is the prefered way, but not by me (1. I prefer building from source that using a package manager for programs I use most often; 2. for testing purposes).

---

Anyway, here are some suggestions on changes in `src/index.html`:

- add `<meta charset="utf-8">` into `<head>`;
- change the `<title>` from `<%= htmlWebpackPlugin.options.title %>` to something more meaningful (like `romcal`);
- add the missing `<script>` part from above.

**Comment by tukusejssirs** [comment]
BTW, there are some errors even when using the files you provided me in the archive:

![Screenshot from 2020-03-09 19-40-54](https://user-images.githubusercontent.com/5111894/76246401-886f3680-6235-11ea-9a64-3f16664c25b7.png)

**Comment by tukusejssirs** [comment]
A slightly OT request, but this is what would suit me the best: how could I create a `nodejs` script (run solely in terminal)? I have slightly touched regular JS, but never done anything with TS nor `nodejs`. That script would help automate stuff on my end.

I tried the following, but I am sure it is utterly wrong.

```js
#!/usr/bin/env node

var romcalVendor = require('/home/ts/dls/romcal-test/romcal/dist/es5/vendor~romcal.bundle.es5.js');
var romcal = require('/home/ts/dls/romcal-test/romcal/dist/es5/romcal.bundle.es5.js');

// Variables
var userLang = 'sk';

// document.addEventListener("DOMContentLoaded", function(event) {
console.log.addEventListener("DOMContentLoaded", function(event) {
  var userLang = navigator.language || navigator.userLanguage;

  var code1 = document.getElementById("current-locale");
  var node1 = document.createTextNode(userLang);
  code1.appendChild(node1);

  window.romcal
    .calendarFor({
      locale: userLang
    })
    .then(function(dates) {
      var code1 = document.getElementById("romcal-output");
      console.log("dates for the locale", userLang, "are", dates);
      var node1 = document.createTextNode(JSON.stringify(dates));
      code1.appendChild(node1);

      var code2 = document.getElementById("current-locale-1");
      var node2 = document.createTextNode("sk");
      code2.appendChild(node2);
    });
});
```

**Comment by pejulian** [comment]
@tukusejssirs 

I think I understand why you're facing these issues.

> I think I’ve found my issue: Although I have run npm install in the cloned romcal repo root folder, but it did not create dist/ folder and the files in it.

When you clone `romcal` and run `npm install`, you are merely getting the "development" setup. The `/dist` folder is not a part of that setup as it is a *build artifact* generated only when running `npm run build` or `npm run build:dev` in your local machine.

> The other part of the problem lays in the src/index.html file itself: the one in the romcal repo (_F-TypeScript branch), misses the following part I’ve got from the one you gave me in the archive:

Think of `src/index.html` as the "template" for the build process to generate a working `index.html` in `/dist'. When running the build script, this `src/index.html` file runs through the [HtmlWebpackPlugin](https://webpack.js.org/plugins/html-webpack-plugin/) which is transformed into the one seen in `dist/index.html` which in turn will contain the missing scripts you described.

> Therefore, I have a question: how to build romcal (create dist/ folder and the files in it) from cloned romcal repo? I understand, that the npm install romcal@canary is the prefered way, but not by me (1. I prefer building from source that using a package manager for programs I use most often; 2. for testing purposes).

Run the following commands in your machine: 

1. `git clone git@github.com:romcal/romcal.git`
2. `git checkout _F-TypeScript`
3. `npm install`
4. `npm run build`

This will generate the `dist` folder with all the required artifacts for testing locally.

> add <meta charset="utf-8"> into <head>;

Done by the webpack plugin I mentioned above [here](https://github.com/romcal/romcal/blob/_F-TypeScript/webpack.config.ts#L119-L126)

> change the <title> from <%= htmlWebpackPlugin.options.title %> to something more meaningful (like romcal);

I'll look into this.

**Comment by pejulian** [comment]
> BTW, there are some errors even when using the files you provided me in the archive:
> 
> ![Screenshot from 2020-03-09 19-40-54](https://user-images.githubusercontent.com/5111894/76246401-886f3680-6235-11ea-9a64-3f16664c25b7.png)

This is actually expected output from `romcal`. I've added input validation when initializing `romcal`. In this context, relevant validation rules can be found [here](https://github.com/romcal/romcal/blob/_F-TypeScript/src/validators/romcal-config.validator.ts#L21-L24). 

My guess is that the browser passed `en-US` to the library. But since `en-US` is not defined [here](https://github.com/romcal/romcal/blob/_F-TypeScript/src/locales/index.ts#L12-L19), `romcal` will reject this configuration and fallback to defaults.

To get this to work, we could simply create a `en-US` entry in `locales/index.ts` and add the corresponding `en-US.ts` file in the `locales` folder. It might make sense to create this file (even if it is empty) because most browsers seem to use `en-US` as its default locale.

**Comment by pejulian** [comment]
> A slightly OT request, but this is what would suit me the best: how could I create a `nodejs` script (run solely in terminal)? I have slightly touched regular JS, but never done anything with TS nor `nodejs`. That script would help automate stuff on my end.
> 
> I tried the following, but I am sure it is utterly wrong.
> 
> ```js
> #!/usr/bin/env node
> 
> var romcalVendor = require('/home/ts/dls/romcal-test/romcal/dist/es5/vendor~romcal.bundle.es5.js');
> var romcal = require('/home/ts/dls/romcal-test/romcal/dist/es5/romcal.bundle.es5.js');
> 
> // Variables
> var userLang = 'sk';
> 
> // document.addEventListener("DOMContentLoaded", function(event) {
> console.log.addEventListener("DOMContentLoaded", function(event) {
>   var userLang = navigator.language || navigator.userLanguage;
> 
>   var code1 = document.getElementById("current-locale");
>   var node1 = document.createTextNode(userLang);
>   code1.appendChild(node1);
> 
>   window.romcal
>     .calendarFor({
>       locale: userLang
>     })
>     .then(function(dates) {
>       var code1 = document.getElementById("romcal-output");
>       console.log("dates for the locale", userLang, "are", dates);
>       var node1 = document.createTextNode(JSON.stringify(dates));
>       code1.appendChild(node1);
> 
>       var code2 = document.getElementById("current-locale-1");
>       var node2 = document.createTextNode("sk");
>       code2.appendChild(node2);
>     });
> });
> ```

Yes, I don't think this will work. The `node` environment doesn't have a `window` object (there's only `global` and that has a different use entirely). Similarly, the event listener wouldn't exist either because there's no `document` object to be had in `node` env.

Some time back, we used to have this `/bin` folder in the repository. It contained a bash script that ran `romcal` commands directly from the terminal when invoked. Perhaps we can reconsider adding this again.

**Comment by emagnier** [comment]
> My guess is that the browser passed en-US to the library. But since en-US is not defined here , romcal will reject this configuration and fallback to defaults.

> Perhaps I can soften the error message to a warning instead since romcal still continues to work by falling back to its internal defaults when an unsupported locale is passed to it.

Yes, romcal should only warn the user, since the fallback is a normal behaviour (a `en-US` file isn't necessary). In any case, it's very good to provide feedback on the console on how romcal behave.

**Comment by tukusejssirs** [comment]
> When you clone `romcal` and run `npm install`, you are merely getting the "development" setup. The `/dist` folder is not a part of that setup as it is a _build artifact_ generated only when running `npm run build` or `npm run build:dev` in your local machine.

Okay. Again, this must be noted in the contributor’s/developer’s guide (even if the behaviour changes).

> Think of `src/index.html` as the "template" for the build process to generate a working `index.html` in `/dist'. When running the build script, this `src/index.html`file runs through the [HtmlWebpackPlugin](https://webpack.js.org/plugins/html-webpack-plugin/) which is transformed into the one seen in`dist/index.html` which in turn will contain the missing scripts you described.

I understand what you describe, but after running `npm install && npm run build`, there is no `dist/index.html` file (nor any HTML file in `dist/ nor its subdirectories). Of course, now I can modify the `src/index.html` file.

> My guess is that the browser passed `en-US` to the library. But since `en-US` is not defined [here](https://github.com/romcal/romcal/blob/_F-TypeScript/src/locales/index.ts#L12-L19), `romcal` will reject this configuration and fallback to defaults.

Your guess is right, but I use `en-GB` set everywhere where possible (therefore in the browser too). But as you and @emagnier already said, it should a warning (if really needed), not an error. I think that this kind of warning should be output only when _debugging_, but I don’t about it if it is a mere warning.

**Comment by emagnier** [comment]
Addressed on https://github.com/romcal/romcal/pull/250.
