### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by FGasper** [romcal/romcal#2]
Hello,

How difficult would it be to have this library support browser JavaScript?

Thank you!

-FG

**Comment by pejulian** [comment]
Try running browserify on this module.
I haven't tried it yet but it may just work.
I have plans to make this module available as a bower package but I haven't had the time to do it just yet.

**Comment by padrecedano** [comment]
Hi. It's very interesting this code. It will very useful if we can use this into web sites with PHP/Javascript. 

And for use with mobile applications, for example Android and iOS... it will be possible to have the code for this kind of use?

Thanks.

**Comment by geoviedo** [comment]
Hola padre cedano. Yo tambien estaba teniendo la misma idia. Es un buen codigo, con algunos cuantos cambios que se tiene que hacer a lo que se refiere al breviario, pero no mucha cosa. Seria bueno se se puedo utilizar calendarios liturgicos y de varios paises. Yo estoy tratando de ver como adaptarlo para android, pues en mi caso lo necesito para Taiwan. El problema que tengo es que no existe el misal ni el lecctionario digital, solo existe el que usan en hongkong. Si deseas podemos entar en contacto. Abrazos.

**Comment by padrecedano** [comment]
Claro geoviedo. En mi página [deiverbum.org](http://www.deiverbum.org) estoy organizando una serie de recursos en bases de datos relacionales. Estoy organizando en dichas bases de datos toda la liturgia de la Iglesia (liturgia de las horas, oraciones y lecturas de la misa, santoral, homilías, comentarios patrísticos, etc.). La idea es combinar ese contenido y mostrarlo según el día litúrgico, o mostrar contenido específico según el interés de los usuarios. Por eso estoy buscando un programa que me calcule automáticamente el día litúrgico y en base a él mostrar cualquier contenido litúrgico, algo parecido a la página universalis que muestra todo el contenido de un día litúrgico. Pero la página es en inglés y tienen aplicaciones, pero de pago. Yo quisiera poder crearlo y ofrecerlo de forma gratuita. El proyecto romcal es bastante completo y sería ideal poder disponer de él en javascript/PHP, en Java y en Swift para aplicaciones móviles.

**Comment by pejulian** [comment]
Hi Padre Cedano and Jerry,

Perhaps one way to make romcal more accessible for this use case is to
write a simple web application that exposes APIs that can be consumed by
external services.
The API basically call romcal's methods and returns data in JSON format.
That way romcal will be language and platform agnostic.

Do let me know your thoughts.

Also, please feel free to contribute to the translations and dates for
romcal for Spanish/celebrations in Spain :)

PS: Padre Cedano, amazing work you have done on deiverbum.org! Is the
content localizable to other languages?



2016-03-08 18:51 GMT+08:00 padrecedano <notifications@github.com>:

> Claro geoviedo. En mi página deiverbum.org <http://www.deiverbum.org>
> estoy organizando una serie de recursos en bases de datos relacionales.
> Estoy organizando en dichas bases de datos toda la liturgia de la Iglesia
> (liturgia de las horas, oraciones y lecturas de la misa, santoral,
> homilías, comentarios patrísticos, etc.). La idea es combinar ese contenido
> y mostrarlo según el día litúrgico, o mostrar contenido específico según el
> interés de los usuarios. Por eso estoy buscando un programa que me calcule
> automáticamente el día litúrgico y en base a él mostrar cualquier contenido
> litúrgico, algo parecido a la página universalis que muestra todo el
> contenido de un día litúrgico. Pero la página es en inglés y tienen
> aplicaciones, pero de pago. Yo quisiera poder crearlo y ofrecerlo de forma
> gratuita. El proyecto romcal es bastante completo y sería ideal poder
> disponer de él en javascript/PHP, en Java y en Swift para aplicaciones
> móviles.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pejulian/romcal/issues/2#issuecomment-193724094>.
>



-- 
Thanks & Regards,
*Julian Pereira*

**Comment by geoviedo** [comment]
Hi Padre Cedano and Julian.
I am a missionary priest. I had also the same ideia, to build an App about liturgy. There are already two good apps that I use, iBreviary (english, spanish, others) and iBreviarium (chinese). But sometimes they don't have something that I need. One problem is that the liturgical calendar is not compatible with the calendar of the country I am (in this moment Taiwan); second in the iBreviarium, is using the liturgical text from Hong Kong and there are some differences in text of Taiwan.
It could be great if there was a free app that i could select the liturgical calendar and text according to the country. (Some countries in Latino-America use the text in latinoamerican version and other the text from Spain) 
Maybe we could build that app together and, for sure, there will be people who are going to join us.

**Comment by pejulian** [comment]
I am working on a ES6 revamp of this module which is compiled down to ES5 using babel and webpack.
We can then have a bundle.js file for including directly in browsers,
Checkout the romcal-es6 branch.

**Comment by emagnier** [comment]
Browser support has been added in the upcoming `1.3.0` (which will be released this week).
This is the first version of a frontend/browser support, and will need some improvements in the future (decrease the size of the library, lazy load calendar and localization stuffs...).

**Comment by tukusejssirs** [comment]
@emagnier, so is this issue already fixed? You still don’t use the special words like `fix` in the _merge messages_, and thus GitHub does not closes the issues for us.

I think that the improvements should be moved out of this issue.

**Comment by emagnier** [comment]
@FGasper, @padrecedano and @geoviedo: The new version of romcal (`1.3.0-rc2`) is now published, so you can have a try of this library in the browser.
FYI the frontend/browser library will be generated here `dist/romcal.bundle.min.js`, after running the `npm install` command on the `romcal` dir.

Like I mentioned in my comment above, there is still a place for improvements. They might be addressed in new issues. In the meantime, I'm closing this one.

@tukusejssirs this feature has been addressed for a while (by @pejulian) but wasn't available for everyone since romcal wasn't published yet.
