### ISSUE TITLE
skSK: missing feasts

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#21]
I’ve just found out that in Slovakian calendar there is no feast of Our Lady, Queen of Peace, but only in Argentinian one. However, in Argentina they celebrate it on 24th Jan, but in Slovakia we have (probably) the same feast on [24th Aug](https://lc.kbs.sk/?den=20180822) (‘Panny Márie Kráľovnej’ literally means ‘[memorial] of the Virgin Mary the Queen’, as we (1) usually name the feasts/memorials/etc in genitive (the preposition ‘of’ has the same function in English) and (2) we usually (or even never) use ‘Our Lady’ as the name of Mary (though we could use ‘Naša Pani’).

**Comment by pejulian** [comment]
@tukusejssirs 
Thanks for spotting it!
If you're not already adding the memorial in a pull request, I can do so.

**Comment by tukusejssirs** [comment]
Add Memorial of St Margaret of Hungary (`saintMargaretOfHungary`), celebrated on 17th Nov, to `src/slovakia.mjs` [src](https://lc.kbs.sk/?den=20181117).

**Comment by tukusejssirs** [comment]
Add Optional Memorial of St Florian (`saintFlorianMartyr`), celebrated on 4th May, to `src/slovakia.mjs` ([src](https://lc.kbs.sk/?den=20180504)).

**Comment by tukusejssirs** [comment]
Add Memorial of Sts Andrew Zorard and Benedict (`saintsAndrewZorardAndBenedictHermits`), celebrated on 17th Jul, to `src/slovakia.mjs` ([src](https://lc.kbs.sk/?den=20180717)).

**Comment by tukusejssirs** [comment]
Fixed by merging #46.
