### ISSUE TITLE
typo: change `blessedHrzonataMartyr` to `blessedHroznataMartyr

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#35]
While (still) translating the keys in `skSk.mjs`, I’ve just found out that you have typo in the name and value of `blessedHrzonataMartyr` (see [Hroznata](https://cs.wikipedia.org/wiki/Hroznata) article on Czech Wiki).

My suggestion is to change key and its value to the following:
```bash
"blessedHroznataMartyr": "Blessed Hroznata, Martyr"
```

**Comment by emagnier** [comment]
This is now fixed and merged. Thanks!
