### ISSUE TITLE
bug: missing feasts

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#37]
St Bernadette Soubirous (`saintBernadetteSoubirousVirgin`) is (according to the [General Calendar](https://en.wikipedia.org/wiki/General_Roman_Calendar) celebrated on 18th Apr in France, Hungary, and Slovenia only, although according to [English](https://en.wikipedia.org/wiki/Bernadette_Soubirous) and [French](https://fr.wikipedia.org/wiki/Bernadette_Soubirous) wiki, it should be celebrated on 16th Apr worldwide (in the General Calendar) and on 18th Apr in France only. I have no other info (yet) on the matter though.

**Comment by tukusejssirs** [comment]
You probably accidently removed/overwritten `saintBrigidVirgin` key with `saintBridgetOfSwedenReligious` in `src/calendar/ireland.mjs`:
```bash
$ grep -inA2 saintBridgetOfSwedenReligious ../calendars/ireland.mjs 
39:      "key": "saintBridgetOfSwedenReligious",  # change this to `saintBrigidVirgin`
40-      "type": Types[4],
41-      "moment": moment.utc({ year: year, month: 1, day: 1 }),
```

**Comment by tukusejssirs** [comment]
Like in Poland, also in Slovakia we have a celebration called `dedicationOfAParticularChurch`. We celebrate it (always, even if it falls on Sunday) on [26th Oct](https://lc.kbs.sk/?den=20181026) (roll down the page—it’s below the ferial) as Solemnity.

This celebration is celebrated only in consecrated churches of which the consecration date is unknown (hence the title _Výročie posviacky chrámov, ktorých deň posviacky je neznámy_, or _Anniversary of consecration of churches, when the date of consecration is unknown_). I believe that the same rule applies in Poland, too.

**Comment by tukusejssirs** [comment]
Add `saintFaustinaKowalskaVirginAndReligious` (Optional Memorial) on [5th Oct](https://lc.kbs.sk/?den=20181005) in `slovakia.mjs`.

**Comment by tukusejssirs** [comment]
Add `saintJoseDeAnchietaPriest` (Memorial) on [9th Jun](https://en.wikipedia.org/wiki/General_Roman_Calendar#Spain) in `spain.mjs`

**Comment by tukusejssirs** [comment]
In Slovakia, on **every Saturday of Ordinary Time, on which does not fall any memorial/feast/solemnity (i.e. it is only ferial or only optional memorials are celebrated on that day)**, we have an optional memorial of _Our Lady [celebrated] on Saturday_ (sk: Panny Márie v sobotu). However, I have no idea, how to set the day of the celebration, therefore I did not included it in the pull request.

**Comment by jarosz** [comment]
> In Slovakia, on every Saturday (...)

Same in Poland.

> However, I have no idea, how to set the day of the celebration, therefore I did not included it in the pull request.

I have a dirty hack in mind with a loop before
`return Utils.localizeDates(_dates);`
which would add these memorials (keys with incremented index appended to the end) to the `_dates ` array

**Comment by tukusejssirs** [comment]
> I have a dirty hack in mind with a loop before `return Utils.localizeDates(_dates);`, which would add these memorials (keys with incremented index appended to the end) to the `_dates` array.

@emagnier, what do you think on this? How could we implement the `Saturday Memorial of the Blessed Virgin Mary`?

And both of you: do you know if it is included in the `general.js` calendar or specific national calendars?

**Comment by emagnier** [comment]
Actually this isn't possible to do it without a hack. Celebration dates are computed within the scope of a year, 1 date per year per celebrations.

But it could be interesting to add a way to set recurring dates, in the scope of a month or a week, within the general scope of the liturgical year (this might be interesting for votive mass for example).

This optional memorial of Our Lady exists also in France. I believe it's a tradition in the roman church, that could be integrated in the general calendar.

I've created a feature request: #135

Also I might recommend to wait this feature to be implemented for adding the optional memorial of _Our Lady_ (instead using a hack).

**Comment by tukusejssirs** [comment]
I’ve looked at this complex issue and I believe that there only two things not fixed yet:
- the Saturday memorial of Our Lady (moved to #135);
- `dedicationOfAParticularChurch` (moved to #136).

As for the `dedicationOfAParticularChurch`, I believe that this is a celebration that should be in the `general.js`. Slovak official Liturgical Calendar (Direktorium) lists this celebration in each its release, although this celebration is **not* to be celebration where the dedication date is known (then, this should be celebrated on that particular date).

Closing this issue.
