### ISSUE TITLE
Duplicate entries for the same date

### ISSUE THREAD

**Issue by jarosz** [romcal/romcal#52]
Hi.

Some time have passed since the last time I used this software. I'm running this test code
```
var romcal = require('romcal')

var test = romcal.calendarFor({
  year: 2019,
  country: 'poland',
  locale: '',
  christmastideEnds: 'o',
  epiphanyOnJan6: true,
  corpusChristiOnThursday: true,
  ascensionOnSunday: true,
  type: 'calendar',
});

console.log(test);
```
And the first two entries are:

> [ { moment: '2019-01-01T00:00:00.000Z',
>     type: 'WEEKDAY',
>     name: '8th day in the Octave of Christmas',
>     data: { season: [Object], meta: [Object], calendar: [Object] },
>     key: '8ThDayInTheOctaveOfChristmas',
>     source: 'l' },
>   { moment: '2019-01-01T00:00:00.000Z',
>     type: 'SOLEMNITY',
>     name: 'Mary, Mother of God',
>     data:
>      { season: [Object],
>        meta: [Object],
>        calendar: [Object],
>        prioritized: true },
>     key: 'maryMotherOfGod',
>     source: 'c' },

So there are two entries for 2019-01-01. Is this a bug or a feature? Should romcal decide which is more important and discard the other one, or should I take care of it manually?

**Comment by tukusejssirs** [comment]
Hi, @jarosz! I am not a developer and @pejulian is silent since April 2018. I can’t really help you, but still thank you for submitting this issue.

I hope that pejulian or some other dev would pick the development up to make even better.

**Comment by jarosz** [comment]
I believe I can fix it myself, but I don't know if I should (is it a feature or a bug).

I've noticed a romcal-es6 branch which has been developed more actively, but I don't know how to run it and I can't check if it behaves the same.

**Comment by tukusejssirs** [comment]
As I understand it, `romcal-es6` is dev branch, `master` is stable one (sort of the source code ‘last release’).

I believe that _Mary, Mother of God_ has priority over the Christmas octave, but don’t think it is true in any other octave, however I don’t know.

On the other hand, even if you create merge request, I can’t merge it as Ichave no such privileges. If @pejulian won’t break the silence, I think the best way would be to take the development in our hands, but that would require someone with coding skills who would like to offer up their time for this project.

As for running `romcal-es6`, I was unable doing so, too, but I didn’t investigate it in depth. I think only pejulian known knows the ‘key’ to run it.

**Comment by jarosz** [comment]
> I believe that _Mary, Mother of God_ has priority over the Christmas octave, but don’t think it is true in any other octave, however I don’t know.

Only octave of Easter has priority over solemnities and romcal can handle it properly, but the replacement function returned data before replacement.

**Comment by emagnier** [comment]
This has been fixed and merged into master. Closing.

**Comment by tukusejssirs** [comment]
@emagnier, is there a reason to make `master` more diverged in comparison to `romcal-es6`?
