### ISSUE TITLE
Fork a new main repo?

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#54]
As @pejulian is silent since April 2018, I am thinking about  creating new main repo. What do you think? Are you in?

@jarosz, @Dev1an , @emagnier, @agbloomfield

**Comment by emagnier** [comment]
Or maybe @pejulian could you add @tukusejssirs as a Collaborator of `romcal`?
He already made goods suggestions and PRs, and I think it's important this project continues to live, be improved in quality, and attract new contributors.

Because of my studies I don't have to much time to contribute on it actually, but I try to keep an eye on it. I have a few projects and ideas where `romcal` would take very important part ;)

**Comment by jarosz** [comment]
Well, you've already forked this repository. Just write in README, that you're maintaining it because of the original developer's silence. I've seen your TODO list with some good ideas. Keep up the good work. 

I use romcal once a year to generate a calendar file. I don't really need new features, only bugfixes.

**Comment by emagnier** [comment]
Continue to maintain it from a fork is the thing to do, if @pejulian is still keeping the silence.
But before, I think it's better to give him a few days to get his feedback.

If @pejulian is fine to add @tukusejssirs has a Collaborator of this repo, we will also keep the original issue tracker (and its history), existing github stargazers, don't have to modify the git remote repo URL, keep the original status (not with a fork flag) on the github repo page...

This project don't have (yet) to much followers and is catering a niche need. So as much as possible I would suggest avoiding to get this repo looking dying or getting new posts in the issue tracker, without easily know that a fork is taking over it (I know it's easy to find with a quick Github search, but well..., and not all developers are familiar with Github).

**Comment by tukusejssirs** [comment]
Well, I am open to any option except for the ‘death’ of `romcal`. :)

Still, I don’t think that I am the right person to own the forked repo or be the collaborator of this repo, as I am not a coder (at least I am not that good at coding—otherwise you would see some of my coding contribution). However, I am looking forward to future, when `romcal` would be globally (i.e. in the whole world) used, even a little hope that the Holy See and/or the bishop conferences would use and recommend to use it. Nevertheless, I am open to manage this repo, contribute some ideas, feature requests, localisations, celebrations list and some ‘copy-paste’ coding.

I do learn javascript in my free time (of which I have not much) just because of `romcal` to be able to contribute more.

So, okay, I’ll wait for @pejulian ‘to give him a few days to get his feedback’, as @emagnier suggested. I can see that @pejulian is not silent in his other repos; he made some commits to `pejulian/jangelusliew` on 6 Dec 2018. :)

**Comment by agbloomfield** [comment]
I can try to find time to contribute again; I’ve been very busy with two young kids and a new job, but I think it’s an important project — and would be beneficial for several other projects too.

**Comment by tukusejssirs** [comment]
@agbloomfield, we would be grateful for any kind of contribution. :smiley:

While still waiting for @pejulian’s response, I created a list of tasks which I think we should deal with in the near future. Feel free to comment it or add any suggestions.

- [ ] [Microsoft acquired GitHub](https://github.blog/2018-06-04-github-microsoft/) → should we fear another [EEE](https://en.wikipedia.org/wiki/Embrace,_extend,_and_extinguish) attempt and move to another git host (e.g. [NotABug.org](notabug.org))?
- [ ] create an [organisation](https://help.github.com/articles/creating-a-new-organization-from-scratch/) (`romcal`) and transfer the main repo `romcal` there; set up owners, maintainers, contributors;
- [ ] issue tracker (if changing git host): recreate all open issues with concise issue summary and link to the original repo;
- [ ] choose l10n/i18n tool;
- [ ] make a bash/text and html output work again [I coud not use it last time I tried in `romcal-es6`; if it’s working, we need to make it reproducable on (ideally on freshly installed) Linux and Windows with the list of all steps required];
- [ ] deal with the Travis Cl errors on some pull requests and then merge them;
- [ ] create/fullfil/update the community standard:
  - [ ] `contributing.md`; e.g. https://github.com/atom/atom/blob/master/CONTRIBUTING.md;
  - [ ] `description.md`;
  - [ ] `code_of_conduct.md`; e.g. https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md;
  - [ ] issue template; read https://help.github.com/articles/about-issue-and-pull-request-templates/;
  - [ ] pull request template; read https://help.github.com/articles/about-issue-and-pull-request-templates/;
  - [ ] `readme.md`, `readme.[lang].md`: move most of it to other files (like contributing, wiki) … e.g. https://github.com/robb/Cartography;
  - [ ] `authors.md`; e.g. https://github.com/sinatra/sinatra/blob/master/AUTHORS.md;
  - [ ] `contributors`;
  - [ ] `history` → `changelog`;
  - [ ] (`maintainance`);
  - [ ] `version`; a plain-text file that contains version number only; probably should be auto-updated somehow; e.g. https://github.com/sinatra/sinatra/blob/master/VERSION;
  - [ ] `support`; e.g. https://github.com/atom/atom/blob/master/SUPPORT.md;
- [ ] create `romcal.io` website;
- [ ] ? create a twitter account for annoucements;
- [ ] create a list of features to be added in the future; let there be features divided into sub-features (which compose the features).

**Comment by pejulian** [comment]
Hi all,

For some reason, I missed out all the notifications coming from this repository. Thank you @tukusejssirs for reaching out to me via email to alert me on what I've been missing out!

I would like to thank everyone who has contributed in one way or another to this project. It would be sad indeed if romcal falls into disuse. I on my part have been quite tied up with other commitments and hence took a break from active contributions here.

I am open to making all of you in this discussion here contributors to this project. My goal is to make romcal a comprehensive library that is flexible and versatile enough to meet the needs of as many people as possible. Therefore, I am more than happy to include all of you into this project,

Thoughts/comments?

**Comment by pejulian** [comment]
Also, the romcal-es6 branch has fixes and features that should be merged and released. From there, we can continue building features and fixing bugs.

**Comment by tukusejssirs** [comment]
@pejulian, what do you rhink about creating an org?

**Comment by pejulian** [comment]
Done! And I’ve invited all of you to become members to it.

**Comment by tukusejssirs** [comment]
Thank you, @pejulian, for coming back and for making us contributors, as well as creating `romcal` org. :)

And please, check my [previous comment](https://github.com/romcal/romcal/issues/54#issuecomment-461996319) and comment on it. I create separate issues later.

**Comment by jarosz** [comment]
> Also, the romcal-es6 branch has fixes and features that should be merged and released. From there, we can continue building features and fixing bugs.

I agree. Can you provide a guide for running romcal-es6 after checking out the branch? There is a command line tool in bin (not working out of the box with node v10.14.1) and a html file (not working out of the box with Chrome 71.0.3578.98, with same message like #55).

**Comment by tukusejssirs** [comment]
> I am open to making all of you in this discussion here contributors to this project. ([src](https://github.com/romcal/romcal/issues/54#issuecomment-462372533))

> Done! And I’ve invited all of you to become members to it. ([src](https://github.com/romcal/romcal/issues/54#issuecomment-462400012))

@pejulian, the quotes above are somewhat contradictory. We all are _members_ of `romcal` org, however only @emagnier is a _contributor_. Maybe this is what you wanted (then disregard this comment). :)

**Comment by tukusejssirs** [comment]
Just to inform you, I’ve to @pejulian via email again. He’s quite busy right now and comes back asap.

**Comment by pejulian** [comment]
@tukusejssirs, 
Thanks for reaching out again.
I've created a team for contributions and associated it with the romcal repository.
You all should now have contributing access to the romcal repo.
