### ISSUE TITLE
Create `CODE_OF_CONDUCT.MD`

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#59]
I suggest to create `CODE_OF_CONDUCT.MD` and copy there the [Contributor Covenant v1.4](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html). I read it and I think is good.

**Comment by tukusejssirs** [comment]
Note that in the file, we need to place a repo email. I believe @pejulian used his email, though we might create separate one.

**Comment by TobiTenno** [comment]
I don't have access to it, but there is the CI email, that could forward to each of us, esp if we're able to add it as a send alias for ourselves. I'll make a COC and use the CI email for now, and we can discuss on the PR
