### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#60]
I think we should create `VERSION`, a plain-text file that contains version number only. [Here](https://github.com/sinatra/sinatra/blob/master/VERSION)’s an example from Sinatra repo.

We could use [Semantic Versioning 2.0.0](semver.org) rules.

Probably the `VERSION` file should be auto-updated/auto-generated somehow; consider using [semantic-release](https://github.com/semantic-release/semantic-release).

**Comment by tukusejssirs** [comment]
Also we should place in the documentation how we do the release cycle and how we create new version.

I think a proper release (and all release in general, be it major, minor or patch) should have the following (let’s say) attributes after they are merge to master:

- a tag (like `v1.2.0` has);
- a GitHub release (like `v1.2.0` has);
- an npm release (like `v1.2.3` has).

And I would like to note that we should include proper release notes what has changed since the last release. Currently, you merge directly to `master` (sort of) any single commit. I think it would be better to have a dev branch were we would check and test if everything is working and then do a squash merge of all commits with release notes in the merge description. The `git log` would be usable and pretty again. :smiley:

**Comment by emagnier** [comment]
The version # is already well managed by NPM in the manifest file (`packages.json`). I don't see the value of a new `VERSION` file. And this will break the `npm version` before publishing a new package.

There is also an existing `HISTORY.md` that document the changelog as we go along.

And concerning the versioning, it's important to know that, but here I think it's out of scope of this project. If we start to document that, we will then have to document how to code Javascript... etc. There are already a lot of articles over the internet concerning versioning, best practices, architecture... We generally don't read too much documentation, and the romcal documentation itself is already a challenge. This is my point of view, to stay concise, and for not to scatter.

**Comment by tukusejssirs** [comment]
Okay, you’re right. I’m closing this issue.
