### ISSUE TITLE
`README.MD` cleanup

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#61]
We should clean up the `README.MD`. I think it’s a little bit bloated and contains too many details. I bdlieve @pejulian used it single place to publish the documentation and everything else.

My proposal is that this file should contain:
- short description of `romcal`;
- examples of usage;
- installation guide;
- build guide;
- links to the documentation, etc.

There might be some other sections, but ideally it should be kept short.

Parts of the current file should be moved for example to documentation (#57).

Example [README.MD](https://github.com/robb/Cartography) how it should look.

File could be translated into other languages in a form of separate files named `README.[lang].MD`, e.g. `README.skSk.MD`. The links to all languages should be at the beginning of all of these files.

**Comment by tukusejssirs** [comment]
I have started to move the docs from `README.md` to the Wiki. I have also improved the wording, information and/or formatting. Note that I did this on 29 Jan 2019, bu I have forgotten to add this comment here.

I have used these `README.md` sections:
- badges;
- short description;
- Description;
- Features;
- Module Robustness & Data Integrity;

For now I have skipped these sections:
- Contributing to romcal
- Revisions
- Credits

I still need to process the rest of the `README.md`.

I’d like to hear any suggestions how to improve the documentation.

---

- Fixed to link to [_Mysterii Paschalis_](https://www.vatican.va/content/paul-vi/en/motu_proprio/documents/hf_p-vi_motu-proprio_19690214_mysterii-paschalis.html) (now using a link to vatican.va; the former link did not contain whole document);
- Created pages:
   - [Thorough-description](https://github.com/romcal/romcal/wiki/Thorough-description)
   - [Documentation rules](https://github.com/romcal/romcal/wiki/Documentation-rules)
   - [Localization rules](https://github.com/romcal/romcal/wiki/Localization-rules)

- Updated pages:
   - [Home](https://github.com/romcal/romcal/wiki)

- Unchanged pages:
   - [Contributor’s guide](https://github.com/romcal/romcal/wiki/Contributor%E2%80%99s-guide)

**Comment by pejulian** [comment]
> I have started to move the docs from `README.md` to the Wiki. I have also improved the wording, information and/or formatting. Note that I did this on 29 Jan 2019, bu I have forgotten to add this comment here.
> 
> I have used these `README.md` sections:
> 
> * badges;
> * short description;
> * Description;
> * Features;
> * Module Robustness & Data Integrity;
> 
> For now I have skipped these sections:
> 
> * Contributing to romcal
> * Revisions
> * Credits
> 
> I still need to process the rest of the `README.md`.
> 
> I’d like to hear any suggestions how to improve the documentation.
> 
> * Fixed to link to [_Mysterii Paschalis_](https://www.vatican.va/content/paul-vi/en/motu_proprio/documents/hf_p-vi_motu-proprio_19690214_mysterii-paschalis.html) (now using a link to vatican.va; the former link did not contain whole document);
> * Created pages:
>   
>   * [Thorough-description](https://github.com/romcal/romcal/wiki/Thorough-description)
>   * [Documentation rules](https://github.com/romcal/romcal/wiki/Documentation-rules)
>   * [Localization rules](https://github.com/romcal/romcal/wiki/Localization-rules)
> * Updated pages:
>   
>   * [Home](https://github.com/romcal/romcal/wiki)
> * Unchanged pages:
>   
>   * [Contributor’s guide](https://github.com/romcal/romcal/wiki/Contributor%E2%80%99s-guide)

I totally agree that `README.md` has become a gigantic file that needs cleaning up. So far I think what you've done is really great:- separating the chapters into pages in the Wiki. I have nothing more to add for now except that once you've reached an agreeable first draft with the Wiki, we can create a feature branch that cleans up the actual `README.md`. We can also use this feature branch to add README's in other languages as you have suggested.

**Comment by emagnier** [comment]
Addressed on https://github.com/romcal/romcal/pull/250.
