### ISSUE TITLE
Create `romcal` logo/icon

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#62]
It would be nice if we would have a logo for both `romcal` org and repo. They might be the same, but alo different. :)

I am not a graphics designer, although I could create something simple (like my profile ‘picture’).

**Comment by tukusejssirs** [comment]
Just a note: I think it’d be nice to have:
- big logo (wide, in the shape of a rectangle);
   - this one would be used on the future website (like `romcal.io`);
- small logo (in the shape of a square):
   - this one would be used as the GitHub account logo and as a favicon of the future website (like `romcal.io`).

**Comment by emagnier** [comment]
I had some ideas on it, and took the time to do something this afternoon.

![romcal](https://user-images.githubusercontent.com/1045997/70720431-15b4f480-1cf4-11ea-8272-60b54119bf76.png)
![romcal io](https://user-images.githubusercontent.com/1045997/70720439-18afe500-1cf4-11ea-9a1b-4ba0f7ccdabd.png)

I wanted something modern, but not too flashy. The logo has a blue circled background, that highlight the warm colors inside. It represents a calendar, with a [cross pattée](https://en.wikipedia.org/wiki/Cross_patt%C3%A9e). The cross is the symbol of Christians, and this specific cross is especially used in missal and liturgical books. The red color is often used in calendar logos, it also reminds the color of sections and descriptions of liturgical books, and more generally, this is the traditional color added on black and white old books. This is also the color of the blood of the Christ. The brown color of the cross and the name will remind the wood. It's a neutral color that will also emphasize the elegance.
The logo also uses the [Crimson](https://fonts.google.com/specimen/Crimson+Text) font, which is a font family for book production in the tradition of beautiful old-style typefaces. This font has an Open Font License (OFL), and is very close to the Minion Pro font family from Adobe, or all the Garabond fonts.

I could spend more time explaining all my choices and the details, but this is a difficult exercise for me to do it in English :)

The logo is available in two versions, including one with the future website.
Just for information, I'm adding a draft version below showing the alignments between the left logo and the name.

![romcal guided](https://user-images.githubusercontent.com/1045997/70721455-e0110b00-1cf5-11ea-9c10-e24e613302a6.png)

**Comment by tukusejssirs** [comment]
Nice, @emagnier! :smiley:

A few notes:
1. I suggest to create a separate repo for the image sources.
   - I’d be nice if the sources would be in a text format (like SVG), but even if the source file would not be a text file (like Gimp’s XCF), it would be nice to have in the repo, but then I would suggest to setup Git LFS.
   - The repo would also serve for versioning the images.
2. The font looks nice!
3. Personally, I like it more when the font colour is absolute black (`#000000`).
4. Though the TLD (`.io`) looks nice in the faded (gray) colour, I wouldn’t use it at all. :smiley:
5. I like the cross very much, but I’d like to suggest to make it red as the rubrics. I prefer absolute red (`#ff0000`), but sometimes the rubrics are in a darker shade of red (the cross might be of different red that in red in calendar to emphasise its importance). And maybe I would suggest to restyle the cross (but still let it be pattée; I like the style of the 5th cross from left in [this image](https://images.squarespace-cdn.com/content/v1/563a8a20e4b097ff29a8565f/1549327846467-OTX6UTUKK9PEKOY9UNWX/ke17ZwdGBToddI8pDm48kMCLRJ70-VXb4jBNtLDuALUUqsxRUqqbr1mOJYKfIPR7LoDQ9mXPOjoJoqy81S2I8N_N4V1vUb5AoIIIbLZhVYwL8IeDg6_3B-BRuF4nNrNcQkVuAT7tdErd0wQFEGFSnHWG-R0__mW35KD09SED9i0c2EECpSuZFyLStDr8m76WIDIG6rbt1a7LkrWRHXyQZw/Garrigos.jpg?format=750w)).
6. I haven’t even noticed the _brown_ colour. It looked to me like a slightly lighter black (or a very dark gray). Still I think that the text could be black. The circle around the cross could be also black. The cross itself red. :smiley:
7. The logo looks somewhat cartoonish to me. It is not bad (actually it looks great!), but I like logos that are more simple (even outlined ones). But that is me. :smiley:
8. I am not good at graphical design, so I won’t post anything since you have already created a logo that looks much better than anything I could produce. :smiley:

**Comment by emagnier** [comment]
Thanks for the feedback. I've started to work on some variants, i'll post them when it's ready.

**Comment by tukusejssirs** [comment]
@emagnier, I think we might like to have a separate repo for the logo source(s). What do you think? And don’t forget to license your work! :smiley:

**Comment by emagnier** [comment]
Yes, I'll think about that. Also I can export it to SVG, it's all in vector graphic.

**Comment by tukusejssirs** [comment]
Do as you wish. :smiley:

The repo might contain multiple image formats. I have no idea what program you use, but if you use Photoshop, you might share there PS file, if Gimp, it might be an XCF file. Of course, you might export SVG and/or PNG file, too.

**Comment by emagnier** [comment]
@tukusejssirs I use Affinity Designer, a competitor of Adobe Illustrator.

---

Below, a few new variants (1-4). And a new one (5), my favourite. Do let me know your thoughts!

1. 
![romcal v2 2](https://user-images.githubusercontent.com/1045997/73558050-b309ea80-4452-11ea-8fca-c2caa8cc0a1e.png)
---
2.
![romcal v3 0](https://user-images.githubusercontent.com/1045997/73558056-b69d7180-4452-11ea-958d-f3618977156a.png)
---
3.
![romcal v3 0a](https://user-images.githubusercontent.com/1045997/73558070-bd2be900-4452-11ea-8a00-a026f11a217c.png)
---
4.
![romcal v3 2](https://user-images.githubusercontent.com/1045997/73558113-d2a11300-4452-11ea-88ab-b0b86c514f0e.png)
---
5.
![romcal v4 2b](https://user-images.githubusercontent.com/1045997/73573298-51a64380-4473-11ea-9cc0-74db19fc6e3c.png)
---
Ping @pejulian.

**Comment by emagnier** [comment]
After playing with different variants of the logo, I created a new one (4th on my previous comment). 

![romcal v4 2d](https://user-images.githubusercontent.com/1045997/73591017-b9977100-44e9-11ea-87fa-dc816aa849a0.png)

I've a little bit enforced the serif of the cross, with subtle curves on each ends. The cross is bigger, and will match better with the serif font (Crimson) used for "romcal". The cross use the red color usually used for rubrics. The bigger cross will also highlight better the christian content of this library.
"romcal" is in a very dark grey, very close to black. These 2 colors remind the colors traditionally used in liturgical books.
The pictogram behind the cross reminds a calendar, both in a clean, simple and a modern style. 
Together, the traditional style of the cross and the serif font, and the cross which make fit in a more modern style of the calendar, will express what romcal is: a library using modern technologies, while keeping all the tradition and the heritage of the liturgy.

**Comment by tukusejssirs** [comment]
@emagnier, I like latest (4) version very much!

The only thing I see is the vertical alignment. In the original version, you aligned the letters (particularly the letter `'`) with the days in the calendar pictogram. I think you should enlarge the icon with with a side as long as the `l` is high and move it on the baseline (i.e. bottom side of the pictogram should be on the same line as the `romcal` word bottom).

**Comment by pejulian** [comment]
My vote is definitely on the 4th logo.

I heartily agree with @emagnier 's reasonings supporting the design:- especially the part that says "using modern technologies, while keeping all the tradition and heritage of the liturgy".

This was precisely the thought I had in my mind sometime around the feast of St. Anne's back in 2014 that spurred me to start working on this module.

**Comment by pejulian** [comment]
@emagnier,

Hope you don't mind; I've taken the liberty of using this awesome logo as the profile avatar of our `romcalproject` machine user 😄.

**Comment by emagnier** [comment]
@pejulian sure! I still need to work a little bit and propose something to address last @tukusejssirs's comment (I'm in front of too many things presently, it's why I didn't made update yet). And as soon as it's ready and final, I will generate the logo image in different size for different situations. As suggested by @tukusejssirs the best place for that might be a new `romcal-logo` repo to store everything related to it.

**Comment by tukusejssirs** [comment]
I think that the @romcalproject bot user should have a unique avatar. I don’t say it cannot _contain_ the romcal logo—I think it should! The only difference might be the `BOT` word underneath the logo. But this is just a thought, not a requirement. :smiley:

**Comment by emagnier** [comment]
@pejulian and @tukusejssirs thank you very much for your last comments!

Here 2, and probably latest versions of the logo. The first one (A) is the same I've already published above (nothing new). On the second one (B), I've adjusted a bit the size of the logo to make it a little bigger. It might also address @tukusejssirs's comment. I personally prefer the B.

I've also added versions showing the guided lines from Affinity Designer (to see the alignments).

Let me know your thoughts!

---
### A
![romcal v4 2d](https://user-images.githubusercontent.com/1045997/74091456-0a920100-4ab8-11ea-8c0c-8eab7b19657e.png)
<img width="1197" alt="romcal v4 2d_" src="https://user-images.githubusercontent.com/1045997/74091458-0f56b500-4ab8-11ea-9caa-07527104df09.png">
---
### B
![romcal v4 2e](https://user-images.githubusercontent.com/1045997/74091459-14b3ff80-4ab8-11ea-8970-7341dc438ad7.png)
<img width="1197" alt="romcal v4 2e_" src="https://user-images.githubusercontent.com/1045997/74091461-17aef000-4ab8-11ea-95d9-2cea8e75b87f.png">

**Comment by emagnier** [comment]
And you can see the B one in action here: https://github.com/romcal/romcal-api

**Comment by tukusejssirs** [comment]
I like the B much more than the A.

On the alignment: I was not clear enough in my previous comment. I think that the logo should be moved upwards on the [baseline](https://cdn.idevie.com/wp-content/uploads/2016/06/median.jpg) with the logo height same as the height of the letter `l` (maybe it would be even better if the logo height would be the same as the capital letter in that font; see the [cap line](https://cdn.idevie.com/wp-content/uploads/2016/06/median.jpg)). Alternatively, if the logo would look to small to you, you could enlarge the logo, but I think that the vertical centre of the logo should be in the middle of the height of letter `l` (alternatively: in the middle of the capital letter).

Again: see it as suggestion, not as a requirement.

**Comment by emagnier** [comment]
Included in the documentation of the upcoming romcal v2, since https://github.com/romcal/romcal/pull/250.

A separated repo for the logo is on the way.
