### ISSUE TITLE
Travis CI: Running `apt-get` update disabled by default

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#66]
Should we enable it? Here in the Travis CI warning:

```bash
Running apt-get update by default has been disabled.
You can opt into running apt-get update by setting this in your .travis.yml file:
  addons:
    apt:
      update: true
```

**Comment by emagnier** [comment]
What the purpose of enable it? Is it relevant, and will it give a benefit for testing romcal? 
Is there any disadvantages?

**Comment by tukusejssirs** [comment]
Well, I have no idea. :smiley:

The reason I have opened this issue, is that the Travis output this warning. It might not be needed at all, because all dependencies are installed by `npm`, therefore the only dependency is `npm` (from the `apt` point of view). And also, opting into running it would slow down the Travis builds (which are currently already quite slow, as in one Travis build there are 8 different builds for `npm` of different versions).

So, I you have no need of any package to be up-to-date, you might just simply close this issue. If you need `npm` to be up-to-date, you should run `apt update` and `apt -y install npm` (in the Travis YAML syntax, of course).
