### ISSUE TITLE
Travis CI: Build dist: trusty?

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#67]
I have just noticed that the Travis CI using for `romcal` (Ubuntu) Trusty, i.e. 14.04 LTS aka Trusty Tahr, which reaches its end of life on 30 Apr 2019. I recommend to change it. However, currently I can’t access Travis CI settings for `romcal`, until @pejulian gives me the access. Still, I have no idea if I can solve it as I am not familiar with Travis CI, though it looks quite versatile. :)

**Comment by emagnier** [comment]
Romcal `v3` is now using [GitHub Action](https://github.com/romcal/romcal/actions) (using `ubuntu-latest`), instead of Travis.
