### ISSUE TITLE
Proof the code for typos and code style

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#68]
Proof the code for typos (mainly in comments) and code style.

**Comment by TobiTenno** [comment]
we added code style checks in #479 

@tukusejssirs @emagnier what kind of "typos" do we want to check for?

would something like [this](https://github.com/aotaduy/eslint-plugin-spellcheck) cover what you're talking about?

**Comment by tukusejssirs** [comment]
> what kind of "typos" do we want to check for?

Back then, I wanted to check the code _manually_ for incorrect grammar and typos. Some code comments (incl TsDoc) test descriptions are/were not grammatically correct and their style is not consistent. I wanted to fix that.

> would something like [this](https://github.com/aotaduy/eslint-plugin-spellcheck) cover what you're talking about?
I didn’t know about that ESLint plugin, but I like it! However, it checks (mostly) only typos. We should still go through it manually and make the style consistent and fix other grammatical, non-typo issues.

As for consistency, I am for the definition of clear, consise rules how we want to style/format/name stuff (e.g. `Use American English.`), which should be possibly hosted in the `docs` app (in the monorepo, we could make it a regular packge like `@romcal/docs` which could be published to NPM, but publishing it is not necessary). Another option is to create programmatic checks (like in ESLint) for each rule.

**Comment by TobiTenno** [comment]
i think we need to break out the docs part as a requirement of #57/#157 and keep the scope of this issue to just the typo linting, in my opinion

i agree with making other formatting rules, but i think those would be part of #157

**Comment by TobiTenno** [comment]
so i think code style we've got done, there's problems with the linter i was trying to use for typos, it's far too sensitive and no option for specifying an extra dictionary that i could find, it made everything very hard to work with ...

so i'm gonna close this out, i'm trying to automate this and it's not really something we can automate any more than we already proof as we review
