### ISSUE TITLE
Change ‘national’ to ‘particular’ (calendars)

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#73]
I believe the term used by the Roman Catholic Church is ‘particular calendar’.

**Comment by tukusejssirs** [comment]
Actually, I was _partially_ wrong about the usage. Even _Martyrologium Romanum_, ed. altera (2004) uses both, e.g. in _Prænotanda_, n. 34 (see below), they use `Calendario diœcesis vel nationis` (diocesan or national Calendar), therefore (as I understand it) a _particular calendar_ is a used in a board sense (it can be either national or diocesan or religious calendar), but we can be more specific by using a more specific term when needed. Therefore now I suggest to use it that way; we don’t need to eliminate the usage of _national calendar_, but use is when talk about a calendar for a particular nation/country.

>  [_Martyrologium Romanum_, ed. altera (2004), _Prænotanda_, n. 34 (emphasis mine)]
>
> Quivis Sanctus in Martyrologio Romano inscriptus eligi potest ut titulus ecclesiæ. Si vero de Beato agatur, ab Apostolica Sede indultum petere oportet, nisi Beatus ipse in _**Calendario diœcesis vel nationis**_ iam rite inscriptus sit.

**Comment by emagnier** [comment]
Since we plan to add diocesan calendars in romcal someday, and a feature to be able to extend romcal with any custom calendars (for example a parish calendar), `particular` is still the right term in my point of view.

**Comment by emagnier** [comment]
Addressed on https://github.com/romcal/romcal/pull/250.
