### ISSUE TITLE
Add ferial cycles

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#75]
We should add ferial cycles.

There are two ferial cycles:

- I. cycle (every odd calendar year);
- II. cycle (every even calendar year).

This would helps us later to determine, what reading, etc are used in a particular ferial Mass (#20), but also with #74, #12). We need to add some strings to the `src/locales` just to enable the localisation.

**Comment by emagnier** [comment]
Similar to `cycle` (years A, B and C), the returned object could looks like:
```
data.meta.ferialCycle: {
    key
    value
}
```
Where the key/values could be:
```
odd: 'I. cycle'
even: 'II. cycle'
```
And better, the values should refer to locale keys, so we can get them in any language.

**Comment by emagnier** [comment]
Also the current `data.meta.cycle` (for A B C years) should be renamed to `data.meta.sundayCycle`.

**Comment by tukusejssirs** [comment]
Agreed. I not sure though if it is (by liturgists) called _Sunday cycle_ though; I searched the Net, but have not found a better translation. And also, _Sunday cycle_ is in contrast with _ferial cycle_, so it might be beneficial from this point of view, too. Therefore you can rename it. :smiley:

**Comment by pvanthony** [comment]
Need some clarification. Sunday mass is three year cycle and weekday mass is two year cycle. So by having ferial cycles we can know which reading on a particular weekday. Am I correct?

I ask this because we are trying to automate daily reading audio recordings on the website. Currently we can do the daily saint audio recording which is easy. With romcal, we should be able to automate the Sunday readings because of the Year A B and C.

It looks like we are not able to automate the weekday readings. By adding ferial cycles, we should be able to automate the weekday readings, correct?

I would like to help with this. I am not a programmer but I can help with adding the ferial cycle data for every record. I am assuming that is needed.

**Comment by emagnier** [comment]
Currently, only Sunday cycle (A, B, C) are available from the item property:
```
data.meta.cycle.key
```
where the values of the keys correspond to:
- 0: Year A
- 1: Year B
- 2: Year C

The cycle for the ferias/weekdays (Monday to Saturday) are not yet implemented. But if you need it, you might check that from the current year number.

**Comment by tukusejssirs** [comment]
@pvanthony, as @emagnier has already said, the current solution is to check if the current year (as number) is even or odd.

Which year is the current year? The liturgical year starts with Advent, for example Advent 2019, so the current year is 2019 (even in January 2020 or October 2020), and 2019 is not divisible by 2 without the remainder, therefore the current ferial cycle is I.

Note that we will implement the ferial cycles too, but there is not ETA yet.

**Comment by pvanthony** [comment]
Thank you for the reply and the advice on how to get the ferial cycle.
Could I trouble you for some javascript code to check for the current liturgical year?

**Comment by emagnier** [comment]
In the browser you could get it that way:

```javascript
var today = new Date();
var currentYear = today.getFullYear();

var dates = Romcal.calendarFor({
  year: currentYear
});

var todayCelebration = _.find(dates, function(item) {
  return item.moment.isSame(today), 'day')
});

var sundayCycle = todayCelebration.data.meta.cycle;
var feriaCycle = currentYear % 2 ? 'odd' : 'even';

console.log(today);
console.log(sundayCycle);
console.log(feriaCycle);
```

Note that this exemple will require the [Lodash](https://lodash.com/) library (`_.find`).
Also here the feria cycle will not be accurate during the season of Avent and Christmas (since it's computed without romcal), but I guess you only need it for the ordinary time?

**Comment by tukusejssirs** [comment]
@emagnier, you beat me with your speed! I have created the following code (which is much worse than yours), but it calculates the **correct** ferial cycle. However, the `firstSunAdvent` should be correctly defined (from romcal), but I haven’t been with romcal that much yet, so could you update _your_ code with _some_ of mine?

```js
var today = new Date();
var year = today.getFullYear();
// TODO: Get the date of the First Sunday of Advent
// for that particular year from romcal
var firstSunAdvent = new Date(2020, 10, 29);  // Note that Jan = 0, Dec = 11
var ferialCycle;

if (today < firstSunAdvent) {  // If today is before firstSunAdvent
  // Then substract 1 (one) from year
  year--;
}

// Get the remainder of the year / 2 division
var tmp = year % 2;

if (tmp == 0) {
  ferialCycle = 2;
} else {
  ferialCycle = 1;
}

document.write('Ferial cycle number for ' + year + ' is ' + ferialCycle + '.');
```

**Comment by tukusejssirs** [comment]
@pvanthony, @emagnier, I have finally got it right. Below is working script. I have tested it on romcal v1.3.0 built from source. I have [attached](https://github.com/romcal/romcal/files/4129861/index.txt) modified `index.html` file in which I have tested this script (you need to rename `index.txt` to `anything.html`; GitHub does not allow HTML file attachments).

```js
// If your locale is supported by romcal, it will use it, otherwise it will default to 'en'.
var currentLocale = navigator.language || navigator.userLanguage;
var today = new Date();
var year = new Date().getFullYear();

// Get the dates for year and currentLocale
var dates = Romcal.calendarFor({
	locale: currentLocale,
	year: year
});

// Order the dates by liturgical seasons and get Sundays only
var datesOrderedBySeasons = Romcal.queryFor(dates, {
	group: 'liturgicalSeasons',
	day: 0	// Sun = 0 - Sat = 6
});

// Get the date of the First Sunday of Advent from the datesOrderedBySeasons
// Note: datesOrderedBySeasons is a JSON, but the seasons are arrays
var firstSundayAdvent = new Date(datesOrderedBySeasons.Advent[0].moment);

// Output to console
console.log('Date of the First Sunday of Advent in ' + year + ' is ', firstSundayAdvent + '.');

var ferialCycle;

if (today < firstSundayAdvent) {	// If today is before firstSundayAdvent
	// Then substract 1 (one) from year
	litYearStart = year--;
	litYearEnd = year;
} else {
	litYearStart = year;
	litYearEnd = year++;
}

// Get the remainder of the year / 2 division
var tmp = litYearStart % 2;

if (tmp == 0) {
	ferialCycle = 2;
} else {
	ferialCycle = 1;
}

console.log('Ferial cycle number for the liturgical year ' + litYearStart + '/' + litYearEnd + ' is ' + ferialCycle + '.');
```

**Comment by emagnier** [comment]
I've [updated my previous comment](https://github.com/romcal/romcal/issues/75#issuecomment-579844828) to easily get both Sunday and feria cycles, based on a liturgical date from romcal.

**Comment by tukusejssirs** [comment]
@emagnier, I believe you have missed an opening bracket bracket here in your code:

```js
// Original
return item.moment.isSame(today), 'day')

// Suggested
return item.moment.isSame((today), 'day')
```

The other problem lays in the fact that the current year is the year when the liturgical year starts, not ends (i.e. in liturgical year Advent 2019 to Christ the King Sunday 2020, current year is 2019).

```js
// Original
var feriaCycle = (isTodayBeforeAdvent ? currentYear : currentYear + 1) % 2 ? 'Odd' : 'Even';

// Proposed
var feriaCycle = (isTodayBeforeAdvent ? currentYear -1 : currentYear) % 2 ? 'I' : 'II';
```

**Comment by emagnier** [comment]
Thanks, it was a bad copy paste. Can you hide/collapse your examples so we are not lost between all theses code snippets?

The `feriaCycle` is correct, today we are actually in an `even` cycle, even if the liturgical year started in 2019. In fact, this information is only required for ordinary time, using 2020 as a reference (for the 2019-2020 liturgical year). This is why I didn't make it based on romcal on my first example.

**Comment by tukusejssirs** [comment]
Okay, I have collapsed my scripts.

And on the cycles: you are right. I’ve got it wrong. In 2019/2020 lit. year, the _current year_ is 2020. :smiley:

**Comment by tukusejssirs** [comment]
@emagnier, just a sidenote: I’ve just noticed that you have name the variable as `feriaCycle`. It should be named `ferialCycle` as it is named as _ferial cycle_. _Feria_ is a noun and _ferial_ is an adjective.

**Comment by pvanthony** [comment]
Thank you to both of you for sharing the code to get the Ferial cycle. I do appreciate it very much.
I will try it out.

**Comment by pvanthony** [comment]
Just tried with the master branch and the feature where it shows the "Monday of the 14 week of Ordinary Time" for the date 2020-07-06 does not seem to be there. Can I assume that this will only come in version 2.0?
Currently using the alpha or beta version mentioned in this thread.

Check out what we are trying to achieve at this test site.
https://romcal.sound.sg/iraivarthai/
It will also change colour according to romcal.

The live site is,
https://www.iraivarthai.org/

FYI. Sometime later we will be contributing Tamil translation.

**Comment by emagnier** [comment]
Hello @pvanthony, thanks for your comment and thank you for sharing us your project you are working on!

Yes the next major version will output weekdays by default if the possible memorial for this day is optional.
I plan to make this new major version out for ~ mid-August. But I can't be 100% sure of the ETA (I am still committed to other projects currently).

**Comment by emagnier** [comment]
Done in the `_F-TypeScript` branch (soon in the `dev` branch). Please have look to the corresponding documentation: https://github.com/romcal/romcal/blob/_F-TypeScript/docs/data-output.md#weekday-cycle

**Comment by emagnier** [comment]
Addressed on https://github.com/romcal/romcal/pull/250.
