### ISSUE TITLE
Holy Days of Obligation

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#76]
We should have an option (or parameter/metadata) to denote the Holydays of Obligation.

**Comment by emagnier** [comment]
It's a good idea.

A `boolean` property like `data.meta.holyDayOfObligation`. It should be `false` by default.

**Comment by tukusejssirs** [comment]
Good by me. But I’d like to note that this must be configurable on a celebration level, i.e. the ‘calendarists’ should be able to make changes to this in the calendar settings (e.g. in `general.js` or `france.js`), as the list of HDO is different from calendar to calendar.

**Comment by emagnier** [comment]
Yes definitely. And this is already how things works between these 2 types of calendar.

**Comment by tukusejssirs** [comment]
Just a note to myself: here’s the list all Holy Days of Obligation in Slovakia:

1. 1 Jan: Mary, Mother of God
2. 6 Jan: Epiphany
3. x xxx: Ascension of the Lord (40th day after Easter)
4. x xxx: Corpus Christi (2nd Thursday after the Pentecost Sunday)
5. 29 Jun: Peter and Paul, Apostles
6. 15 Aug: Assumption of the Blessed Virgin Mary
7. 1 Nov: All Saints
8. 8 Dec: Immaculate Conception
9. 25 Dec: Nativity of the Lord (Christmas)

**Comment by tukusejssirs** [comment]
@emagnier, fixing the #210 issue might be necessary before implementing this issue, because of these celebrations are defined in `celebrations.ts`.

**Comment by tukusejssirs** [comment]
@emagnier, are HDOs `extend`-able? I presume yes. If so, when we set them in `general.ts`, we need to `false` some of them in the particular calendars when needed.

If so, we should document this.

**Comment by emagnier** [comment]
Yes, it behave like `date`, or `rank`, or any other extended property.

**Comment by emagnier** [comment]
Addressed on https://github.com/romcal/romcal/pull/250.

**Comment by tukusejssirs** [comment]
@emagnier, below is a list of HDOs for `general` (plus Sundays, of course).

- `mary_mother_of_god`;
- `epiphany`;
- `ascension`;
- `corpus_christi`;
- `peter_and_paul_apostles`;
- `assumption`;
- `all_saints`;
- `immaculate_conception_of_mary`;
- `christmas`;
- `joseph_spouse_of_mary`.

I have just found that `immaculate_conception_of_mary` is not yet set as a HDO. Also that some of the Sunday celebration definitions (where Sundays have some specific name like the Trinity Sunday) are set explicitly as HDOs, others just implicitly.

I’d like to open a PR with fixing the HDOs for `general` and `slovakia` (and later for other calendars), but I’d like to sugget to set all Sundays to be HDOs implicitly. If you agree, I remove all explicit HDO definition for Sundays.

**Update:**

1. And `immaculate_heart_of_mary` is not a HDO. :wink:
2. Actually, only `trinity_sunday` is not set a HDO among Sundays explicitly.

**Update 2:** Proper place to discuss this is PR #281.

**Comment by emagnier** [comment]
@tukusejssirs, from this PR: https://github.com/romcal/romcal/pull/283, all Sundays are now HDO by default.
