### ISSUE TITLE
Create `romcal.io` website

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#80]
We should create `romcal.io` website that would demonstrate the `romcal` functionalities.

**Comment by emagnier** [comment]
It could be build on top of https://github.com/romcal/romcal-api

**Comment by tukusejssirs** [comment]
That would be perfect!

I have used it yet, but I sort of dislike the usage of colons and question marks in the URL (`/api/v1/:calendar-type/:name/:locale/:year?/:month?/:day?`); of couse, the question marks might separate the first part of the URL from variables, but we should not include it the first part. I like the syntax of [Ansible API](https://docs.ansible.com/ansible-tower/2.3.0/html/towerapi/intro.html).

I know that this should be moved to the issues of `romcal-api`. :smiley:

**Comment by emagnier** [comment]
The colons, it's a naming convention when documenting APIs, to point that theses keyword are query parameters. And question mark mean that the parameter is optional.
But if you try to use the API, you don't have to add these `:` and `?` in the URL.

**Comment by tukusejssirs** [comment]
Okay, then. But still have never seem such a naming convention in any APIs I dealt with. :smiley:

**Comment by emagnier** [comment]
It's more used in the codebase with express.js. But I agree that in the final documentation it might be not needed. There is of course place of improvement since it's just the first version of the doc (and at least it exists!)

**Comment by pejulian** [comment]
@tukusejssirs, what are your thoughts on using [netlify](https://www.netlify.com/pricing/) for our proposed website? It has a free tier that includes GIT and CI/CD integration. Perhaps it will be a suitable place to host the static site until we decide to move ahead with the actual domain name we would like to use.

**Comment by tukusejssirs** [comment]
****

**Comment by pejulian** [comment]
> FYI, I did not say that AWS cannot be used. I just wanted to say that if possibly, I would rather not use it.
> 
> I’d like to hear your thoughts on [GitHub Pages](https://help.github.com/en/github/working-with-github-pages/about-github-pages). Is their anything we need (or would like to use) they can’t provide?
> 
> On netlix I can’t comment.
> 
> Anyway, let my comments on this not block you from change, i.e. if you need some web space provider, use it. 😃

I think `gh-pages` is the way to go for now. At least we can get something up and running before we move on to other bigger things. It's good enough for supporting a static site such as what we are planning to build (no database needed, at least for now).

**Comment by tukusejssirs** [comment]
Agreed. :smiley:

**Comment by emagnier** [comment]
FYI, a really first version is up on [romcal.js.org](https://romcal.js.org/) (built on romcal v3).

It still deserves a bit of work (some translations are missing), and it would be nice to demonstrate all the features and data that romcal can offer. But at least a first website version exists.

**Comment by tukusejssirs** [comment]
@emagnier, is there a repo for the website when I could file some issues I found and send some PRs?

**Comment by emagnier** [comment]
Currently, the built sources of the website are temporarily stored here: https://github.com/romcal/romcal.github.io
And the sources are stored in the romcal repository: [/examples/react-app/](https://github.com/romcal/romcal/tree/dev/examples/react-app).

But this is temporarily, as NPM packages for romcal v3 are still not released. Ideally we should probably use https://github.com/romcal/romcal-app to store the source / gh-pages of the romcal website. So I think you could use [this issue tracker](https://github.com/romcal/romcal-app/issues) for the website.

**Comment by tukusejssirs** [comment]
> But this is temporarily, as NPM packages for romcal v3 are still not released. Ideally we should probably use https://github.com/romcal/romcal-app to store the source / gh-pages of the romcal website. So I think you could use [this issue tracker](https://github.com/romcal/romcal-app/issues) for the website.

Well, from my point of view, it does not matter if we store the website in romcal/romcal.github.io or romcal/romcal-app, both repos (or their names) are good enough. If you think `romcal/romcal-app` is better, we should use it and stick to it. :wink:

Anyway, thanks for the info, @emagnier! :wink:

**Comment by TobiTenno** [comment]
romcal.js.org exists, closing this. we have discussions for further doc sites and more examples elsewhere
