### ISSUE TITLE
Code checks and deployment automation

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#81]
We should consider code deployment and checks automation:
  - [ ] consider using [Code Triage](https://www.codetriage.com/) to attract devs, help solve issues;
  - [x] consider using [Danger](https://github.com/danger/danger); probably already using [ESlint](https://eslint.org/);
  - [x] consider using [mention-bot](https://github.com/facebookarchive/mention-bot);
  - [x] consider using [Greenkeeper](https://greenkeeper.io/).

**Comment by TobiTenno** [comment]
@tukusejssirs would you say we cover a bunch of these at this point? could we refine this or close it out? I'm trying triage some of our long-open stuff and see if we can get everything down a bit more manageable so i can close out older issues or small asks like (small) repo docs for contributing, etc.

**Comment by tukusejssirs** [comment]
>   - [ ] consider using [Code Triage](https://www.codetriage.com/) to attract devs, help solve issues;

I think this is still relevant, however, only after we make that more attractive even to a seldom contributor.

>   - [ ] consider using [Danger](https://github.com/danger/danger); probably already using [ESlint](https://eslint.org/);

I think this is not needed anymore, as we use PR checks for this. Maybe it is still useful for stuffs that can’t be done using PR checks. :thinking:

>   - [ ] consider using [mention-bot](https://github.com/facebookarchive/mention-bot);

The repo is archived anf not maintained anymore.

>   - [ ] consider using [Greenkeeper](https://greenkeeper.io/).

Not available anymore. [Snyk](https://snyk.io/) is an alternative if needed.

**Comment by TobiTenno** [comment]
re: greenkeeper/snyk, @tukusejssirs 
we have dependabot set up already, and it does the same general things

**Comment by TobiTenno** [comment]
i think "using" code triage is just a matter of adding the badge, so i'll add myself to it on code triage and submit a PR for the badge, so we can close this out

**Comment by tukusejssirs** [comment]
> re: greenkeeper/snyk, @tukusejssirs we have dependabot set up already, and it does the same general things

While Greenkeeper is an alternative to dependabot, Snyk has more features (e.g. vuln scanning). That said, I don’t require it to be used. :wink:
