### ISSUE TITLE
Fix auto-checking of `romcal` builds made by Travis

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#83]
Related #63 #66 #67

Currently, the builds a not auto-checked by Travis. The reason is currently unknown, though suspect that the Travis configuration is outdated.

**Comment by jarosz** [comment]
I've managed to run and pass Travis CI tests on my fork: jarosz/romcal. I've requested to activate it on romcal/romcal as well, but I believe it has to be accepted by repo owner: @pejulian

**Comment by tukusejssirs** [comment]
Well, I think that @pejulian should grant us (or at least one of us) the access to Travis. However, I think that he uses a personal account for that, so it might be better create something like and _organisation_ account for us all. However, I have no idea if Travis has such a feature.

**Comment by jarosz** [comment]
It's working now. Closing issue.
