### ISSUE TITLE
`romcal` does not localise strings properly

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#85]
I have found another issue (I regard it as major bug): when I change the locale in the example to `sk` (Slovak), most strings are not localised (although they are localised in `skSk.js`). For example:

```bash
300: Object { type: "FEAST", name: "Saints Simon and Jude, Apostles", key: "saintsSimonAndJudeApostles", … }
301: Object { type: "WEEKDAY", name: "utorok of the 30. week of Ordinary Time", key: "utorokOfThe30WeekOfOrdinaryTime", … }
```

**Comment by emagnier** [comment]
This issue was related to the `romcal-es6` branch, and is now fixed (#86).
