### ISSUE TITLE
Rename `weekday` to `feria` (rollback)

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#88]
I suggest to replace `week day` by `feria`, as `feria` is proper name for this. `WEEKDAY` is currently used in `Types.js`.

This issue is somewhat related to #73.

**Comment by emagnier** [comment]
This request has been addressed and merged. Thanks!

**Comment by tukusejssirs** [comment]
It might have been a wrong decision to rename `weekday` to `feria`. I’ve just found the [_General Instruction of the Roman Missal_](https://www.nlo.org.nz/assets/Uploads/NZ-GIRM-Final.pdf) (on the website of National Liturgy Office website of the Catholic Church in Aotearoa New Zealand) from 2010 Roman Missal and it never uses the term _feria_ and always uses the term _weekday_.

**Comment by emagnier** [comment]
This is the same from this doc: https://www.liturgyoffice.org.uk/Resources/GIRM/Documents/GIRM.pdf

As long as romcal v2 is still not out, this is still the good time to improve and change the things.

**Comment by emagnier** [comment]
Addressed on https://github.com/romcal/romcal/pull/250.
