### ISSUE TITLE
Shrove Monday and Tuesday

### ISSUE THREAD

**Issue by emagnier** [romcal/romcal#90]
It seems these 2 dates are rather traditional and cultural, than a real liturgical celebration. 
I wonder if these elements really have their place in the liturgical calendar (for exemple in France we have also nothing about that in the liturgical calendar and they need to be removed).

**Comment by tukusejssirs** [comment]
Well, I think so too. The current General Roman Calendar does not have these, but some particular calendars might include them as a _heritage_ from the historical calendars (before the Second Vatical Council).

If you want them to be removed, I suggest to keep the keys (for future use in historical calendars, #23, and the Extra-Ordinary Calendar #51). I agree on removing the definitions in `general.js` (and `drop` definitions in particular calendars).

**Comment by emagnier** [comment]
Yes, this is a thing I'll do.

**Comment by emagnier** [comment]
PR merged.
