### ISSUE TITLE
Include default settings in national calendar files

### ISSUE THREAD

**Issue by emagnier** [romcal/romcal#91]
I think a **calendar** file for a specific country should include the **default settings for that country:**
- `christmastideEnds`
- `epiphanyOnJan6`
- `corpusChristiOnThursday`
- `ascensionOnSunday`

These options will remain editable from the romcal API.
But if they are not redefined, will apply first the values defined in the calendar file of the selected country (if exists). 
If they are not either defined in the calendar country file, it will use the romcal default settings (like actually).

The advantage here is that we can select a calendar of any country, without have to know what are the specific rules for that country. They will be applied automatically.

**Comment by tukusejssirs** [comment]
I agree.

I think that there should be set _all_ settings and there there should not be a fallback to the settings in `general.js`. This would result in (sort of) duplicate settings (between calendars), but this would make the settings more (human-)readable/consistent IMO. But in the end, I wouldn’t care even if you decide to implement it the way the locales are (reverting to the settings defined in `general.js`, where there should the default settings be defined).

**Comment by emagnier** [comment]
This has been implemented in #162.
