### ISSUE TITLE
Use lowerCamelCase in filenames in `src/constants/`

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#95]
I have just noticed that the files in `constants` are named in UpperCamelCase (in contrary with the usual/JS lowerCamelCase). I would suggest to rename that the following way:
- `Cycles.js` → `cycles.js`;
- `LiturgicalColors.js` → `liturgicalColors.js`;
- `LiturgicalSeasons.js` → `liturgicalSeasons.js`;
- `PsalterWeeks.js` → `psalterWeeks.js`;
- `Titles.js` → `titles.js`;
- `Types.js` → `types.js`.

**Comment by emagnier** [comment]
It's a naming convention in Javascript application development.

PascalCase is used when we export a constructor / class / singleton / function library / bare object...
And camelCase when we export-default a function.

**Comment by tukusejssirs** [comment]
I did not know that. :)
